/**
 * 🎬 Видео — SillyTavern extension (author: derryanna)
 *
 * Adds a 🎬 button to every image generated by SLAY Images
 * (`img[data-iig-instruction]` inside `.mes_text`), asks a vision model
 * (through a Connection Manager profile) for a Wan 2.2 image-to-video prompt,
 * lets the user edit it in a popup and sends the job to a local bridge.
 * When the render is done the video is uploaded to SillyTavern and attached
 * to the message via `message.extra.media` (native ST 1.18 video attachment).
 */

import { extension_settings, getContext } from '../../../extensions.js';
import { saveSettingsDebounced, eventSource, event_types, getRequestHeaders } from '../../../../script.js';
import { callGenericPopup, POPUP_TYPE, POPUP_RESULT } from '../../../popup.js';
import { ConnectionManagerRequestService } from '../../shared.js';
import { proxies } from '../../../openai.js';
import { MEDIA_TYPE } from '../../../constants.js';

const MODULE = 'tavern_video';
const LOG = '[🎬 Видео]';
const TOAST_TITLE = '🎬 Видео';

const POLL_MS = 5000;
const MAX_TEXT_CHARS = 1500;
const MAX_POLL_ERRORS = 6;
const DONE_STATUS_TTL_MS = 15000;

const LORAS = ['none', 'nsfw', 'dreamlay'];
const DELIVER = ['chat', 'tg', 'both'];
const RESOLUTIONS = [480, 720];

export const DEFAULT_SYSTEM_PROMPT = [
    'You turn one frame of an adult anime roleplay (all characters are adults, fictional, consenting) into a prompt for the Wan 2.2 image-to-video model.',
    'Wan reads natural English sentences, not tags. The frame already fixes who is there and where; your job is the MOTION of the next few seconds.',
    'Output JSON only: {"lora": "none|nsfw|dreamlay", "prompt": "..."}',
    'lora: "dreamlay" when the frame shows an explicit sex act, "nsfw" for nudity or sensual touching, "none" otherwise.',
    'The prompt is ONE paragraph of 60-100 words, present tense, third person, built in this order:',
    '1. Only if lora is dreamlay: the single trigger word for the position comes first — bl0wj0b, d0ubl3_bj, d0gg1e, c0wg1rl, r3v3rs3_c0wg1rl or m15510n4ry.',
    '2. "Anime style," plus 3-5 words on the look of the frame (soft painterly 2D illustration, warm palette, clean lines...).',
    '3. One sentence with the people named by what is visible, never by name: "the silver-haired man", "the blonde woman", their pose, clothing or nudity, exactly as in the frame.',
    '4. The main motion: ONE continuous action with simple direct verbs (strokes, bobs, thrusts, leans, breathes), how it repeats or continues and its rhythm (slow, steady, rhythmic). Then 1-2 secondary motions: hair sways, chest rises, cloth shifts, steam drifts, light flickers.',
    '5. Camera and light: "static shot", the shot size that matches the frame (close-up, medium close-up, medium shot, wide shot), the lighting (soft morning light, warm lamp light, dim room...).',
    '6. Finish with "smooth continuous motion, high quality".',
    'Rules: describe only what can move from this exact frame; no new characters, no scene change, no cuts, no "then" or "after"; no negations (never write "no", "without", "not"); no tag lists; the image-model tags you get are for reference only, do not copy them; be literal and explicit when the frame is explicit; no disclaimers.',
    'Example: {"lora": "none", "prompt": "Anime style, soft painterly illustration with a warm palette. The silver-haired man leans over the sleeping blonde woman in bed and slowly strokes her hair, his hand moving in gentle repeated passes from her temple to the pillow. Her chest rises and falls with slow breathing, her lips part slightly, loose strands of hair shift under his fingers. Static shot, medium close-up, soft overcast morning light from the window. Smooth continuous motion, high quality."}',
].join('\n');
// earlier releases: v1 asked for character names via {NAMES}, v2 wrote two-line FRAME/VIDEO-ish prompts; saved copies are migrated
const LEGACY_PROMPT_MARKERS = ['Use these English names for the characters: {NAMES}', 'Never use character names: say "the man"'];

const DEFAULTS = Object.freeze({
    bridgeUrl: '/comfy-bridge',
    bridgeKey: '',
    profileId: '',
    direct: false,
    sec: 5,
    res: 480,
    lora: 'none',
    loraStrength: 1.0,
    deliver: 'chat',
    systemPrompt: DEFAULT_SYSTEM_PROMPT,
    maxTokens: 800,
});

const MEDIA_VIDEO = MEDIA_TYPE?.VIDEO ?? 'video';

// ---------------------------------------------------------------------------
// Settings
// ---------------------------------------------------------------------------

function getSettings() {
    if (!extension_settings[MODULE] || typeof extension_settings[MODULE] !== 'object') {
        extension_settings[MODULE] = {};
    }
    const settings = extension_settings[MODULE];
    for (const [key, value] of Object.entries(DEFAULTS)) {
        if (settings[key] === undefined || settings[key] === null) {
            settings[key] = value;
        }
    }
    if (LEGACY_PROMPT_MARKERS.some(marker => String(settings.systemPrompt || '').includes(marker))) {
        settings.systemPrompt = DEFAULT_SYSTEM_PROMPT;
    }
    return settings;
}

const SETTINGS_HTML = `
<div id="tavern_video_settings" class="tavern-video-settings">
    <div class="inline-drawer">
        <div class="inline-drawer-toggle inline-drawer-header">
            <b>🎬 Видео</b>
            <div class="inline-drawer-icon fa-solid fa-circle-chevron-down down"></div>
        </div>
        <div class="inline-drawer-content">
            <div class="tv-section">
                <h4><i class="fa-solid fa-plug"></i> Мост</h4>
                <div class="tv-row"><label for="tv_bridge_url">Адрес</label><input id="tv_bridge_url" class="text_pole" type="text" placeholder="/comfy-bridge" autocomplete="off"></div>
                <div class="tv-row"><label for="tv_bridge_key">Ключ</label><input id="tv_bridge_key" class="text_pole" type="password" placeholder="пусто = ключ из SLAY" autocomplete="new-password"><div id="tv_key_toggle" class="menu_button tv-key-toggle" title="Показать / скрыть"><i class="fa-solid fa-eye"></i></div></div>
                <div class="tv-row"><label for="tv_profile">Профиль</label><select id="tv_profile" class="text_pole"></select></div>
                <p class="tv-hint">Профиль Connection Manager с моделью, которая видит картинки (Gemini Flash подходит).</p>
                <label class="checkbox_label tv-check" for="tv_direct"><input id="tv_direct" type="checkbox"><span>Слать запрос напрямую (если через профиль модель не видит картинку)</span></label>
                <div id="tv_test" class="menu_button tv-test"><i class="fa-solid fa-wifi"></i> Тест</div>
            </div>
            <div class="tv-section">
                <h4><i class="fa-solid fa-sliders"></i> Параметры видео</h4>
                <div class="tv-row"><label for="tv_sec">Секунды</label><input id="tv_sec" class="text_pole" type="number" min="1" max="10" step="1"></div>
                <div class="tv-row"><label for="tv_res">Разрешение</label><select id="tv_res" class="text_pole"><option value="480">480p</option><option value="720">720p</option></select></div>
                <div class="tv-row"><label for="tv_lora">LoRA</label><select id="tv_lora" class="text_pole"><option value="none">none</option><option value="nsfw">nsfw</option><option value="dreamlay">dreamlay</option></select></div>
                <div class="tv-row"><label for="tv_lora_strength">Сила LoRA</label><input id="tv_lora_strength" class="text_pole" type="number" min="0" max="2" step="0.05"></div>
                <p class="tv-hint">LoRA модель выбирает сама по кадру; это значение — запасное, если она не ответила JSON-ом. В попапе всё можно поменять.</p>
                <div class="tv-row"><label for="tv_deliver">Куда</label><select id="tv_deliver" class="text_pole"><option value="chat">чат</option><option value="tg">телеграм</option><option value="both">оба</option></select></div>
            </div>
            <div class="tv-section">
                <h4><i class="fa-solid fa-brain"></i> Промпт для модели <div id="tv_sysprompt_reset" class="menu_button tv-reset" title="Вернуть промпт по умолчанию"><i class="fa-solid fa-rotate-left"></i> сброс</div></h4>
                <textarea id="tv_sysprompt" class="text_pole" rows="8"></textarea>
            </div>
        </div>
    </div>
</div>`;

function populateProfiles() {
    const select = document.getElementById('tv_profile');
    if (!select) return;
    const settings = getSettings();
    const profiles = getContext().extensionSettings?.connectionManager?.profiles ?? [];

    select.innerHTML = '';
    select.add(new Option('— выбери профиль —', ''));
    for (const profile of profiles) {
        const details = [profile.api, profile.model].filter(Boolean).join(', ');
        const label = details ? `${profile.name} (${details})` : profile.name;
        select.add(new Option(label, profile.id));
    }
    select.value = profiles.some(p => p.id === settings.profileId) ? settings.profileId : '';
}

function bindSettingsUi() {
    const settings = getSettings();
    const container = document.getElementById('extensions_settings2') || document.getElementById('extensions_settings');
    if (!container) {
        console.warn(LOG, 'Settings container not found');
        return;
    }
    container.insertAdjacentHTML('beforeend', SETTINGS_HTML);

    const $url = $('#tv_bridge_url').val(settings.bridgeUrl);
    const $key = $('#tv_bridge_key').val(settings.bridgeKey);
    const $direct = $('#tv_direct').prop('checked', !!settings.direct);
    const $sec = $('#tv_sec').val(settings.sec);
    const $res = $('#tv_res').val(String(settings.res));
    const $lora = $('#tv_lora').val(settings.lora);
    const $strength = $('#tv_lora_strength').val(settings.loraStrength);
    const $deliver = $('#tv_deliver').val(settings.deliver);
    const $sysprompt = $('#tv_sysprompt').val(settings.systemPrompt);
    populateProfiles();

    const save = () => saveSettingsDebounced();

    $url.on('input', () => { settings.bridgeUrl = String($url.val()).trim(); save(); });
    $key.on('input', () => { settings.bridgeKey = String($key.val()).trim(); save(); });
    $direct.on('change', () => { settings.direct = $direct.prop('checked'); save(); });
    $('#tv_profile').on('change', function () { settings.profileId = String($(this).val() || ''); save(); });
    $sec.on('input', () => { settings.sec = clampInt($sec.val(), 1, 10, DEFAULTS.sec); save(); });
    $res.on('change', () => { settings.res = RESOLUTIONS.includes(Number($res.val())) ? Number($res.val()) : DEFAULTS.res; save(); });
    $lora.on('change', () => { settings.lora = LORAS.includes(String($lora.val())) ? String($lora.val()) : 'none'; save(); });
    $strength.on('input', () => { settings.loraStrength = clampFloat($strength.val(), 0, 2, DEFAULTS.loraStrength); save(); });
    $deliver.on('change', () => { settings.deliver = DELIVER.includes(String($deliver.val())) ? String($deliver.val()) : 'chat'; save(); });
    $sysprompt.on('input', () => { settings.systemPrompt = String($sysprompt.val()); save(); });
    $('#tv_key_toggle').on('click', () => {
        const show = $key.attr('type') === 'password';
        $key.attr('type', show ? 'text' : 'password');
        $('#tv_key_toggle i').toggleClass('fa-eye', !show).toggleClass('fa-eye-slash', show);
    });
    $('#tv_test').on('click', async function () {
        const $btn = $(this);
        if ($btn.hasClass('testing')) return;
        $btn.addClass('testing');
        try {
            const r = await bridgeFetchJson('/', { method: 'GET' });
            if (r?.ok) toastr.success(`Мост на связи · ComfyUI ${r.comfy || '?'}`, TOAST_TITLE);
            else toastr.warning(`Мост отвечает, но ComfyUI ${r?.comfy || 'не отвечает'}`, TOAST_TITLE);
        } catch (error) {
            toastr.error(String(error?.message || error), TOAST_TITLE);
        } finally {
            $btn.removeClass('testing');
        }
    });
    $('#tv_sysprompt_reset').on('click', () => {
        settings.systemPrompt = DEFAULT_SYSTEM_PROMPT;
        $sysprompt.val(DEFAULT_SYSTEM_PROMPT);
        save();
        toastr.info('Системный промпт сброшен', TOAST_TITLE);
    });

    for (const name of ['CONNECTION_PROFILE_CREATED', 'CONNECTION_PROFILE_UPDATED', 'CONNECTION_PROFILE_DELETED']) {
        if (event_types[name]) {
            eventSource.on(event_types[name], () => populateProfiles());
        }
    }
    // Profiles may load after us (loading order) — refresh once the app is ready and when the drawer opens.
    if (event_types.APP_READY) {
        eventSource.on(event_types.APP_READY, () => populateProfiles());
    }
    $('#tavern_video_settings .inline-drawer-toggle').on('click', () => populateProfiles());
}

// ---------------------------------------------------------------------------
// Small helpers
// ---------------------------------------------------------------------------

function clampInt(value, min, max, fallback) {
    const n = parseInt(String(value), 10);
    if (!Number.isFinite(n)) return fallback;
    return Math.min(max, Math.max(min, n));
}

function clampFloat(value, min, max, fallback) {
    const n = parseFloat(String(value));
    if (!Number.isFinite(n)) return fallback;
    return Math.min(max, Math.max(min, Math.round(n * 100) / 100));
}

function debounce(fn, ms) {
    let timer = null;
    return (...args) => {
        clearTimeout(timer);
        timer = setTimeout(() => fn(...args), ms);
    };
}

function stripHtml(html) {
    try {
        const doc = new DOMParser().parseFromString(String(html ?? ''), 'text/html');
        return (doc.body?.textContent ?? '').replace(/[ \t]+\n/g, '\n').replace(/\n{3,}/g, '\n\n').trim();
    } catch {
        return String(html ?? '').replace(/<[^>]*>/g, '').trim();
    }
}

function blobToDataUrl(blob) {
    return new Promise((resolve, reject) => {
        const reader = new FileReader();
        reader.onload = () => resolve(String(reader.result));
        reader.onerror = () => reject(reader.error ?? new Error('FileReader failed'));
        reader.readAsDataURL(blob);
    });
}

function isAbsoluteUrl(url) {
    return /^https?:\/\//i.test(url);
}

function bridgeUrl(path) {
    const base = String(getSettings().bridgeUrl || DEFAULTS.bridgeUrl).trim().replace(/\/+$/, '');
    return base + (path.startsWith('/') ? path : `/${path}`);
}

/**
 * Resolves `video_url` from the bridge: absolute URLs are used as-is, paths are
 * appended to the bridge URL (unless they already start with the bridge path).
 */
function resolveBridgeFileUrl(url) {
    const value = String(url || '').trim();
    if (!value) throw new Error('Бридж не вернул video_url');
    if (isAbsoluteUrl(value) || value.startsWith('data:') || value.startsWith('blob:')) return value;
    const base = String(getSettings().bridgeUrl || DEFAULTS.bridgeUrl).trim().replace(/\/+$/, '');
    const basePath = isAbsoluteUrl(base) ? new URL(base).pathname.replace(/\/+$/, '') : base;
    if (basePath && value.startsWith(`${basePath}/`)) {
        return isAbsoluteUrl(base) ? new URL(value, base).href : value;
    }
    return bridgeUrl(value);
}

/**
 * Bridge key: the extension's own setting, or — when it is empty — the key SLAY Images
 * already uses for the same comfy-bridge endpoint (so the tavern needs it typed in once).
 */
function effectiveBridgeKey() {
    const own = String(getSettings().bridgeKey || '').trim();
    if (own) return own;
    const slay = extension_settings?.slay_image_gen;
    // SLAY stores the endpoint without a leading slash ("comfy-bridge/v1/chat/completions"), compare path-insensitively
    const norm = (v) => String(v || '').trim().replace(/^https?:\/\/[^/]+/i, '').replace(/^\/+|\/+$/g, '').toLowerCase();
    const base = norm(getSettings().bridgeUrl || DEFAULTS.bridgeUrl);
    if (slay?.apiKey && base && norm(slay.endpoint).startsWith(base)) return String(slay.apiKey).trim();
    return '';
}

function bridgeHeaders(extra = {}) {
    const key = effectiveBridgeKey();
    const headers = { ...extra };
    if (key) headers['Authorization'] = `Bearer ${key}`;
    return headers;
}

async function bridgeFetchJson(path, init = {}) {
    const response = await fetch(bridgeUrl(path), {
        ...init,
        headers: bridgeHeaders({ 'Content-Type': 'application/json', ...(init.headers || {}) }),
    });
    const text = await response.text();
    let json = null;
    try { json = text ? JSON.parse(text) : null; } catch { /* not json */ }
    if (!response.ok) {
        const detail = json?.error || json?.detail || text.slice(0, 200) || response.statusText;
        throw new Error(`бридж ответил ${response.status}: ${detail}`);
    }
    if (json === null) throw new Error('бридж вернул не-JSON');
    return json;
}

function formatElapsed(seconds) {
    const total = Math.max(0, Math.floor(Number(seconds) || 0));
    const m = Math.floor(total / 60);
    const s = total % 60;
    return `${m}:${String(s).padStart(2, '0')}`;
}

// ---------------------------------------------------------------------------
// Image → base64 (original resolution)
// ---------------------------------------------------------------------------

function canvasToBase64(img) {
    const canvas = document.createElement('canvas');
    canvas.width = img.naturalWidth || img.width;
    canvas.height = img.naturalHeight || img.height;
    if (!canvas.width || !canvas.height) throw new Error('картинка ещё не загрузилась');
    canvas.getContext('2d').drawImage(img, 0, 0);
    const dataUrl = canvas.toDataURL('image/png');
    return { base64: dataUrl.split(',')[1], mime: 'image/png' };
}

async function imageToBase64(img) {
    const src = img.currentSrc || img.src;
    if (!src) throw new Error('у картинки нет src');
    try {
        const response = await fetch(src);
        if (!response.ok) throw new Error(`HTTP ${response.status}`);
        const blob = await response.blob();
        const mime = (blob.type || '').split(';')[0].trim().toLowerCase();
        if (mime === 'image/png' || mime === 'image/jpeg') {
            const dataUrl = await blobToDataUrl(blob);
            return { base64: dataUrl.split(',')[1], mime };
        }
        // webp/gif/unknown → re-encode to PNG at the same resolution.
        if (img.complete && img.naturalWidth) {
            return canvasToBase64(img);
        }
        const bitmap = await createImageBitmap(blob);
        const canvas = document.createElement('canvas');
        canvas.width = bitmap.width;
        canvas.height = bitmap.height;
        canvas.getContext('2d').drawImage(bitmap, 0, 0);
        return { base64: canvas.toDataURL('image/png').split(',')[1], mime: 'image/png' };
    } catch (error) {
        console.warn(LOG, 'fetch(image) failed, falling back to canvas', error);
        return canvasToBase64(img);
    }
}

// ---------------------------------------------------------------------------
// Vision model → {lora, prompt}
// ---------------------------------------------------------------------------

function getProfile(profileId) {
    const profiles = getContext().extensionSettings?.connectionManager?.profiles ?? [];
    return profiles.find(p => p.id === profileId) ?? null;
}

function buildMessages({ base64, mime, instruction, text }) {
    const settings = getSettings();
    const systemPrompt = String(settings.systemPrompt || DEFAULT_SYSTEM_PROMPT).replace(/\{NAMES\}/g, 'the man and the woman');
    const userText = [
        `Image-model tags (reference only): ${instruction || '(none)'}`,
        '',
        'Scene text:',
        text || '(empty)',
    ].join('\n');
    return [
        { role: 'system', content: systemPrompt },
        {
            role: 'user',
            content: [
                { type: 'text', text: userText },
                { type: 'image_url', image_url: { url: `data:${mime};base64,${base64}`, detail: 'auto' } },
            ],
        },
    ];
}

/**
 * Direct request to ST's chat-completions backend (bypasses Connection Manager),
 * used when the profile is not a chat-completion profile, when the CM path failed
 * or when the user enabled "direct" in settings.
 */
async function directVisionRequest(profile, messages) {
    const context = getContext();
    const settings = getSettings();
    const apiMap = context.CONNECT_API_MAP?.[profile.api];
    const source = apiMap?.source || 'custom';
    const proxyPreset = Array.isArray(proxies) ? proxies.find(p => p.name === profile.proxy) : null;
    const oai = context.chatCompletionSettings || {};

    const body = {
        stream: false,
        messages,
        model: profile.model,
        chat_completion_source: source,
        custom_url: profile['api-url'] || (source === 'custom' ? oai.custom_url : undefined),
        secret_id: profile['secret-id'],
        reverse_proxy: proxyPreset?.url,
        proxy_password: proxyPreset?.password,
        custom_include_body: oai.custom_include_body,
        custom_exclude_body: oai.custom_exclude_body,
        custom_include_headers: oai.custom_include_headers,
        custom_prompt_post_processing: profile['prompt-post-processing'] || undefined,
        max_tokens: settings.maxTokens,
        temperature: 0.7,
        use_sysprompt: true,
    };
    for (const key of Object.keys(body)) {
        if (body[key] === undefined || body[key] === '') delete body[key];
    }

    const response = await fetch('/api/backends/chat-completions/generate', {
        method: 'POST',
        headers: getRequestHeaders(),
        cache: 'no-cache',
        body: JSON.stringify(body),
    });
    const json = await response.json().catch(() => ({}));
    if (!response.ok || json?.error) {
        throw new Error(String(json?.error?.message || json?.error || `HTTP ${response.status}`));
    }
    const content = json?.choices?.[0]?.message?.content
        ?? json?.choices?.[0]?.text
        ?? (Array.isArray(json?.content) ? json.content.filter(p => p.type === 'text').map(p => p.text).join('\n') : json?.content)
        ?? json?.text
        ?? '';
    return typeof content === 'string' ? content : JSON.stringify(content);
}

function isChatCompletionProfile(profile) {
    try {
        return ConnectionManagerRequestService.isProfileSupported(profile)
            && getContext().CONNECT_API_MAP?.[profile.api]?.selected === 'openai';
    } catch {
        return false;
    }
}

function parseModelJson(raw) {
    const settings = getSettings();
    let text = String(raw ?? '').trim();
    text = text.replace(/^```(?:json)?\s*/i, '').replace(/```\s*$/, '').trim();
    const start = text.indexOf('{');
    const end = text.lastIndexOf('}');
    if (start !== -1 && end > start) {
        try {
            const obj = JSON.parse(text.slice(start, end + 1));
            const lora = LORAS.includes(String(obj.lora || '').toLowerCase()) ? String(obj.lora).toLowerCase() : settings.lora;
            const prompt = String(obj.prompt ?? '').trim();
            if (prompt) return { lora, prompt };
        } catch (error) {
            console.warn(LOG, 'model JSON parse failed', error, text);
        }
    }
    if (!text) throw new Error('модель вернула пустой ответ');
    return { lora: settings.lora, prompt: text };
}

async function askVisionModel(payload) {
    const settings = getSettings();
    if (!settings.profileId) throw new Error('выбери профиль подключения в настройках «🎬 Видео»');
    const profile = getProfile(settings.profileId);
    if (!profile) throw new Error('профиль подключения не найден — выбери другой в настройках');

    const messages = buildMessages(payload);
    let raw;
    if (!settings.direct && isChatCompletionProfile(profile)) {
        try {
            const result = await ConnectionManagerRequestService.sendRequest(
                settings.profileId,
                messages,
                settings.maxTokens,
                { stream: false, extractData: true, includePreset: true, includeInstruct: false },
            );
            raw = typeof result === 'string' ? result : result?.content;
        } catch (error) {
            console.warn(LOG, 'Connection Manager request failed, trying direct request', error);
            raw = await directVisionRequest(profile, messages);
        }
    } else {
        raw = await directVisionRequest(profile, messages);
    }
    console.debug(LOG, 'model answer:', raw);
    return parseModelJson(raw);
}

// ---------------------------------------------------------------------------
// Popup
// ---------------------------------------------------------------------------

function escapeHtml(text) {
    return String(text ?? '')
        .replace(/&/g, '&amp;')
        .replace(/</g, '&lt;')
        .replace(/>/g, '&gt;')
        .replace(/"/g, '&quot;');
}

async function showJobPopup({ prompt, lora, previewSrc }) {
    const settings = getSettings();
    const loraOptions = LORAS.map(v => `<option value="${v}"${v === lora ? ' selected' : ''}>${v}</option>`).join('');
    const resOptions = RESOLUTIONS.map(v => `<option value="${v}"${v === Number(settings.res) ? ' selected' : ''}>${v}</option>`).join('');
    const deliverLabels = { chat: 'чат', tg: 'телеграм', both: 'оба' };
    const deliverRadios = DELIVER.map(v => `<label><input type="radio" name="tv_p_deliver" value="${v}"${v === settings.deliver ? ' checked' : ''}> ${deliverLabels[v]}</label>`).join('');

    const wrapper = document.createElement('div');
    wrapper.className = 'tv-popup';
    wrapper.innerHTML = `
        <h3>🎬 Видео</h3>
        ${previewSrc ? `<div class="tv-preview"><img src="${escapeHtml(previewSrc)}" alt=""></div>` : ''}
        <label for="tv_p_prompt">Промпт</label>
        <textarea id="tv_p_prompt" class="text_pole" rows="7"></textarea>
        <div class="tv-grid">
            <label>LoRA <select id="tv_p_lora" class="text_pole">${loraOptions}</select></label>
            <label>Сила <input id="tv_p_strength" class="text_pole" type="number" min="0" max="2" step="0.05" value="${escapeHtml(settings.loraStrength)}"></label>
            <label>Секунды <input id="tv_p_sec" class="text_pole" type="number" min="1" max="10" step="1" value="${escapeHtml(settings.sec)}"></label>
            <label>Разрешение <select id="tv_p_res" class="text_pole">${resOptions}</select></label>
            <label>Seed <input id="tv_p_seed" class="text_pole" type="number" step="1" placeholder="случайный"></label>
        </div>
        <div class="tv-radios"><span>Куда:</span>${deliverRadios}</div>`;
    wrapper.querySelector('#tv_p_prompt').value = prompt;

    let captured = null;
    const capture = () => {
        const seedRaw = String(wrapper.querySelector('#tv_p_seed').value || '').trim();
        const loraValue = String(wrapper.querySelector('#tv_p_lora').value || 'none');
        captured = {
            prompt: String(wrapper.querySelector('#tv_p_prompt').value || '').trim(),
            lora: LORAS.includes(loraValue) ? loraValue : 'none',
            loraStrength: clampFloat(wrapper.querySelector('#tv_p_strength').value, 0, 2, settings.loraStrength),
            sec: clampInt(wrapper.querySelector('#tv_p_sec').value, 1, 10, settings.sec),
            res: clampInt(wrapper.querySelector('#tv_p_res').value, 1, 4096, settings.res),
            seed: seedRaw === '' ? null : clampInt(seedRaw, -2147483648, 4294967295, null),
            deliver: wrapper.querySelector('input[name="tv_p_deliver"]:checked')?.value || settings.deliver,
        };
    };

    const result = await callGenericPopup(wrapper, POPUP_TYPE.CONFIRM, '', {
        okButton: 'Го',
        cancelButton: 'Отмена',
        wide: true,
        allowVerticalScrolling: true,
        onClosing: (popup) => {
            if (popup.result === POPUP_RESULT.AFFIRMATIVE) {
                capture();
                if (!captured.prompt) {
                    toastr.warning('Промпт пустой', TOAST_TITLE);
                    return false;
                }
            }
            return true;
        },
    });

    if (result !== POPUP_RESULT.AFFIRMATIVE || !captured) return null;
    return captured;
}

// ---------------------------------------------------------------------------
// Jobs: create, poll, attach
// ---------------------------------------------------------------------------

/**
 * @typedef {object} JobState
 * @property {string} id
 * @property {string} key
 * @property {string} chatId
 * @property {number} mesId
 * @property {string} src
 * @property {string} deliver
 * @property {string} prompt
 * @property {string} text
 * @property {boolean} error
 * @property {number} errors
 * @property {any} timer
 * @property {boolean} finished
 */

/** @type {Map<string, JobState>} */
const jobs = new Map();
/** @type {Map<string, Array<{mesId:number, path:string, title:string, jobId:string}>>} */
const pendingAttach = new Map();

function jobKey(chatId, mesId, src) {
    return `${chatId}::${mesId}::${src}`;
}

function currentChatId() {
    const context = getContext();
    return String(context.chatId ?? context.getCurrentChatId?.() ?? '');
}

function findImageWrap(mesId, src) {
    const mesEl = document.querySelector(`#chat .mes[mesid="${mesId}"]`);
    if (!mesEl) return null;
    const images = mesEl.querySelectorAll('.mes_text img[data-iig-instruction]');
    const img = Array.from(images).find(i => i.getAttribute('src') === src) ?? null;
    return img ? getWrap(img) : null;
}

function renderStatus(wrap, text, { error = false } = {}) {
    if (!wrap) return;
    let el = wrap.nextElementSibling;
    if (!(el && el.classList && el.classList.contains('tv-status'))) el = null;
    if (!text) {
        el?.remove();
        return;
    }
    if (!el) {
        el = document.createElement('div');
        el.className = 'tv-status';
        wrap.insertAdjacentElement('afterend', el);
    }
    el.classList.toggle('tv-status-error', !!error);
    el.textContent = text;
}

function setJobStatus(job, text, { error = false } = {}) {
    job.text = text;
    job.error = error;
    if (currentChatId() !== job.chatId) return;
    renderStatus(findImageWrap(job.mesId, job.src), text, { error });
}

function statusFromResponse(status) {
    switch (status?.status) {
        case 'queued': {
            const pos = Number(status.position);
            return Number.isFinite(pos) && pos > 0 ? `⏳ в очереди #${pos}` : '⏳ в очереди';
        }
        case 'rendering':
            return `🎬 рендерю ${formatElapsed(status.elapsed)}`;
        case 'done':
            return '✅ готово';
        case 'error':
            return `❌ ${status.error || 'ошибка рендера'}`;
        default:
            return `… ${status?.status || 'неизвестный статус'}`;
    }
}

function getMessage(mesId) {
    const chat = getContext().chat;
    return Array.isArray(chat) ? chat[mesId] : undefined;
}

async function persistJobState(mesId, patch) {
    const message = getMessage(mesId);
    if (!message) return;
    if (!message.extra || typeof message.extra !== 'object') message.extra = {};
    message.extra[MODULE] = { ...(message.extra[MODULE] || {}), ...patch, updated: Date.now() };
    try {
        await getContext().saveChat();
    } catch (error) {
        console.warn(LOG, 'saveChat failed', error);
    }
}

async function createJob({ base64, mime, params, chatId, mesId }) {
    const body = {
        image: base64,
        image_mime: mime,
        prompt: params.prompt,
        sec: params.sec,
        res: params.res,
        seed: params.seed,
        lora: params.lora === 'none' ? [] : [`${params.lora}:${Number(params.loraStrength).toFixed(2).replace(/0$/, '')}`],
        deliver: params.deliver,
        chat: chatId,
        message_id: mesId,
    };
    const json = await bridgeFetchJson('/video/jobs', { method: 'POST', body: JSON.stringify(body) });
    if (!json?.id) throw new Error('бридж не вернул id задачи');
    return String(json.id);
}

function startPolling(job) {
    if (jobs.has(job.key)) {
        clearTimeout(jobs.get(job.key).timer);
    }
    job.errors = 0;
    job.finished = false;
    jobs.set(job.key, job);

    const finish = () => {
        job.finished = true;
        clearTimeout(job.timer);
        jobs.delete(job.key);
        setTimeout(() => {
            if (currentChatId() === job.chatId && !job.error) {
                renderStatus(findImageWrap(job.mesId, job.src), '');
            }
        }, DONE_STATUS_TTL_MS);
    };

    const tick = async () => {
        let status;
        try {
            status = await bridgeFetchJson(`/video/jobs/${encodeURIComponent(job.id)}`, { method: 'GET' });
            job.errors = 0;
        } catch (error) {
            job.errors += 1;
            console.warn(LOG, `poll failed (${job.errors}/${MAX_POLL_ERRORS})`, error);
            if (job.errors >= MAX_POLL_ERRORS) {
                setJobStatus(job, `❌ бридж недоступен: ${error.message}`, { error: true });
                await persistJobState(job.mesId, { status: 'error', error: error.message });
                finish();
                return;
            }
            setJobStatus(job, `${job.text || '⏳'} (нет связи, пробую ещё…)`);
            job.timer = setTimeout(tick, POLL_MS);
            return;
        }

        const text = statusFromResponse(status);
        switch (status.status) {
            case 'done': {
                setJobStatus(job, text);
                finish();
                if (job.deliver === 'chat' || job.deliver === 'both') {
                    try {
                        setJobStatus(job, '⬇️ загружаю видео в чат…');
                        await deliverToChat(job, status);
                        setJobStatus(job, '✅ видео готово');
                        toastr.success('Видео добавлено в сообщение', TOAST_TITLE);
                    } catch (error) {
                        console.error(LOG, 'deliverToChat failed', error);
                        setJobStatus(job, `❌ не смогла прикрепить видео: ${error.message}`, { error: true });
                        toastr.error(`Не смогла прикрепить видео: ${error.message}`, TOAST_TITLE);
                    }
                } else {
                    setJobStatus(job, '✅ готово, отправлено в телеграм');
                    await persistJobState(job.mesId, { status: 'done' });
                }
                return;
            }
            case 'error': {
                setJobStatus(job, text, { error: true });
                toastr.error(status.error || 'ошибка рендера', TOAST_TITLE);
                await persistJobState(job.mesId, { status: 'error', error: status.error || '' });
                finish();
                return;
            }
            default: {
                setJobStatus(job, text);
                job.timer = setTimeout(tick, POLL_MS);
            }
        }
    };

    tick();
}

async function downloadVideoAsBase64(videoUrl) {
    const response = await fetch(videoUrl, { headers: bridgeHeaders() });
    if (!response.ok) throw new Error(`не смогла скачать видео (HTTP ${response.status})`);
    const blob = await response.blob();
    if (!blob.size) throw new Error('видео пустое');
    const dataUrl = await blobToDataUrl(blob);
    return dataUrl.split(',')[1];
}

async function uploadToSillyTavern(name, base64) {
    const response = await fetch('/api/files/upload', {
        method: 'POST',
        headers: getRequestHeaders(),
        body: JSON.stringify({ name, data: base64 }),
    });
    if (!response.ok) {
        throw new Error(`ST не принял файл (HTTP ${response.status}): ${(await response.text()).slice(0, 200)}`);
    }
    const json = await response.json();
    if (!json?.path) throw new Error('ST не вернул путь к файлу');
    return String(json.path);
}

/**
 * Attaches a video to a chat message the ST 1.18 way (`extra.media` array,
 * see `ensureMessageMediaIsArray` / `appendMediaToMessage` in public/script.js).
 * Falls back to the legacy `extra.video` string on older builds.
 */
function attachVideoToMessage(message, path, title) {
    if (!message.extra || typeof message.extra !== 'object') message.extra = {};
    const context = getContext();
    const supportsMediaArray = typeof context.ensureMessageMediaIsArray === 'function';
    if (supportsMediaArray) {
        context.ensureMessageMediaIsArray(message);
        if (!Array.isArray(message.extra.media)) message.extra.media = [];
        message.extra.media.push({ type: MEDIA_VIDEO, url: path, title: title || '' });
    } else {
        message.extra.video = path;
        if (title) message.extra.title = title;
    }
}

function rerenderMessageMedia(mesId, message) {
    const context = getContext();
    const mesEl = $(`#chat .mes[mesid="${mesId}"]`);
    if (!mesEl.length) return;
    if (typeof context.appendMediaToMessage === 'function') {
        context.appendMediaToMessage(message, mesEl);
    } else if (typeof context.updateMessageBlock === 'function') {
        context.updateMessageBlock(mesId, message);
    }
}

async function attachUploadedVideo(chatId, mesId, path, title, jobId) {
    if (currentChatId() !== chatId) {
        const list = pendingAttach.get(chatId) ?? [];
        list.push({ mesId, path, title, jobId });
        pendingAttach.set(chatId, list);
        console.info(LOG, 'chat changed while rendering — video will be attached when the chat is opened again');
        return false;
    }
    const message = getMessage(mesId);
    if (!message) throw new Error(`сообщение #${mesId} не найдено`);
    attachVideoToMessage(message, path, title);
    if (!message.extra[MODULE] || typeof message.extra[MODULE] !== 'object') message.extra[MODULE] = {};
    Object.assign(message.extra[MODULE], { job_id: jobId, status: 'done', video: path, updated: Date.now() });
    await getContext().saveChat();
    rerenderMessageMedia(mesId, message);
    return true;
}

async function deliverToChat(job, status) {
    const videoUrl = resolveBridgeFileUrl(status.video_url);
    const base64 = await downloadVideoAsBase64(videoUrl);
    const name = `slayvideo_${Date.now()}.mp4`;
    const path = await uploadToSillyTavern(name, base64);
    await attachUploadedVideo(job.chatId, job.mesId, path, job.prompt, job.id);
}

async function flushPendingAttachments() {
    const chatId = currentChatId();
    const list = pendingAttach.get(chatId);
    if (!list?.length) return;
    pendingAttach.delete(chatId);
    for (const item of list) {
        try {
            await attachUploadedVideo(chatId, item.mesId, item.path, item.title, item.jobId);
        } catch (error) {
            console.error(LOG, 'pending attach failed', error);
        }
    }
}

/** Resume polling for jobs saved in the chat (after a reload / chat switch). */
function resumeJobsFromChat() {
    const context = getContext();
    const chatId = currentChatId();
    if (!chatId || !Array.isArray(context.chat)) return;
    context.chat.forEach((message, mesId) => {
        const saved = message?.extra?.[MODULE];
        if (!saved?.job_id || ['done', 'error'].includes(saved.status)) return;
        const key = jobKey(chatId, mesId, saved.src || '');
        if (jobs.has(key)) return;
        console.info(LOG, `resuming job ${saved.job_id} for message #${mesId}`);
        startPolling({
            id: String(saved.job_id),
            key,
            chatId,
            mesId,
            src: saved.src || '',
            deliver: DELIVER.includes(saved.deliver) ? saved.deliver : 'chat',
            prompt: saved.prompt || '',
            text: '',
            error: false,
            errors: 0,
            timer: null,
            finished: false,
        });
    });
}

// ---------------------------------------------------------------------------
// Click flow
// ---------------------------------------------------------------------------

async function onVideoButtonClick(img, wrap, btn) {
    const settings = getSettings();
    const mesEl = img.closest('.mes');
    const mesId = Number(mesEl?.getAttribute('mesid'));
    if (!Number.isInteger(mesId)) {
        toastr.error('Не нашла сообщение для этой картинки', TOAST_TITLE);
        return;
    }
    const context = getContext();
    const chatId = currentChatId();
    const message = context.chat?.[mesId];
    const src = img.getAttribute('src') || '';
    const key = jobKey(chatId, mesId, src);

    if (jobs.has(key)) {
        toastr.info('Для этой картинки уже идёт рендер', TOAST_TITLE);
        return;
    }
    if (!String(settings.bridgeUrl || '').trim()) {
        toastr.error('Укажи адрес бриджа в настройках «🎬 Видео»', TOAST_TITLE);
        return;
    }

    btn.classList.add('tv-busy');
    btn.disabled = true;
    try {
        renderStatus(wrap, '🧠 придумываю промпт…');
        const { base64, mime } = await imageToBase64(img);
        const instruction = img.getAttribute('data-iig-instruction') || '';
        const text = stripHtml(message?.mes ?? '').slice(-MAX_TEXT_CHARS);
        const answer = await askVisionModel({ base64, mime, instruction, text });

        renderStatus(wrap, '');
        const params = await showJobPopup({ prompt: answer.prompt, lora: answer.lora, previewSrc: img.currentSrc || src });
        if (!params) return;

        renderStatus(wrap, '📤 отправляю задачу…');
        const jobId = await createJob({ base64, mime, params, chatId, mesId });
        await persistJobState(mesId, { job_id: jobId, status: 'queued', deliver: params.deliver, prompt: params.prompt, src });

        startPolling({
            id: jobId,
            key,
            chatId,
            mesId,
            src,
            deliver: params.deliver,
            prompt: params.prompt,
            text: '⏳ в очереди',
            error: false,
            errors: 0,
            timer: null,
            finished: false,
        });
        renderStatus(wrap, '⏳ в очереди');
    } catch (error) {
        console.error(LOG, error);
        renderStatus(wrap, `❌ ${error?.message || error}`, { error: true });
        toastr.error(String(error?.message || error), TOAST_TITLE);
    } finally {
        btn.classList.remove('tv-busy');
        btn.disabled = false;
    }
}

// ---------------------------------------------------------------------------
// DOM: button injection
// ---------------------------------------------------------------------------

function getWrap(img) {
    return img.closest('.iig-img-wrap, .tv-img-wrap');
}

function attachButton(img) {
    const src = img.getAttribute('src') || '';
    if (!src || src.includes('[IMG:GEN') || src.startsWith('data:image/svg')) return; // SLAY placeholder, not generated yet
    if (img.classList.contains('iig-error-image') || img.closest('.iig-error-placeholder')) return;
    if (!img.parentNode) return;

    let wrap = getWrap(img);
    if (!wrap) {
        wrap = document.createElement('span');
        wrap.className = 'tv-img-wrap';
        img.parentNode.insertBefore(wrap, img);
        wrap.appendChild(img);
    }
    if (wrap.querySelector(':scope > .tv-btn')) return;

    const btn = document.createElement('button');
    btn.type = 'button';
    btn.className = 'tv-btn';
    btn.title = 'Сделать видео из этой картинки';
    btn.setAttribute('aria-label', 'Сделать видео');
    btn.textContent = '🎬';
    btn.addEventListener('click', (event) => {
        event.preventDefault();
        event.stopPropagation();
        onVideoButtonClick(img, wrap, btn);
    });
    wrap.appendChild(btn);

    // Restore a running job's status line after a re-render.
    const mesId = Number(img.closest('.mes')?.getAttribute('mesid'));
    if (Number.isInteger(mesId)) {
        const job = jobs.get(jobKey(currentChatId(), mesId, src));
        if (job?.text) renderStatus(wrap, job.text, { error: job.error });
    }
}

function scanChat() {
    const images = document.querySelectorAll('#chat .mes .mes_text img[data-iig-instruction]');
    for (const img of images) {
        try {
            attachButton(img);
        } catch (error) {
            console.warn(LOG, 'attachButton failed', error);
        }
    }
}

const rescan = debounce(scanChat, 150);

function observeChat() {
    const chatEl = document.getElementById('chat');
    if (!chatEl) return;
    const observer = new MutationObserver((mutations) => {
        for (const mutation of mutations) {
            if (mutation.type === 'attributes') {
                rescan();
                return;
            }
            for (const node of mutation.addedNodes) {
                if (node.nodeType !== Node.ELEMENT_NODE) continue;
                const el = /** @type {Element} */ (node);
                if (el.classList?.contains('tv-btn') || el.classList?.contains('tv-status')) continue;
                rescan();
                return;
            }
        }
    });
    observer.observe(chatEl, { childList: true, subtree: true, attributes: true, attributeFilter: ['src', 'data-iig-instruction'] });
}

// ---------------------------------------------------------------------------
// Init
// ---------------------------------------------------------------------------

jQuery(async () => {
    getSettings();
    bindSettingsUi();
    observeChat();

    const renderEvents = [
        'CHAT_CHANGED',
        'CHARACTER_MESSAGE_RENDERED',
        'USER_MESSAGE_RENDERED',
        'MESSAGE_UPDATED',
        'MESSAGE_EDITED',
        'MESSAGE_SWIPED',
        'MESSAGE_RECEIVED',
        'MESSAGE_SENT',
        'MORE_MESSAGES_LOADED',
        'GENERATION_ENDED',
    ];
    for (const name of renderEvents) {
        if (event_types[name]) eventSource.on(event_types[name], () => rescan());
    }
    eventSource.on(event_types.CHAT_CHANGED, async () => {
        try {
            await flushPendingAttachments();
            resumeJobsFromChat();
        } catch (error) {
            console.warn(LOG, 'CHAT_CHANGED handler failed', error);
        }
        rescan();
    });

    scanChat();
    resumeJobsFromChat();
    console.info(LOG, 'loaded');
});
