/**
 * 🎬 Видео — SillyTavern extension (author: derryanna)
 *
 * Adds a 🎬 button to every image generated by SLAY Images
 * (`img[data-iig-instruction]` inside `.mes_text`), asks a vision model
 * (through a Connection Manager profile) for a Wan 2.2 image-to-video prompt,
 * lets the user edit it in a popup and sends the job to a local bridge.
 * When the render is done the video is uploaded to SillyTavern and attached
 * to the message via `message.extra.media` (native ST 1.18 video attachment).
 * ⏩ continues the motion from the last frame of a finished clip (start_job).
 * 🔗 glues finished clips of a message into one video (POST /video/join, no re-render).
 */

import { extension_settings, getContext } from '../../../extensions.js';
import { saveSettingsDebounced, eventSource, event_types, getRequestHeaders, substituteParams } from '../../../../script.js';
import { callGenericPopup, POPUP_TYPE, POPUP_RESULT } from '../../../popup.js';
import { ConnectionManagerRequestService } from '../../shared.js';
import { proxies } from '../../../openai.js';
import { MEDIA_TYPE } from '../../../constants.js';

const MODULE = 'tavern_video';
const LOG = '[🎬 Видео]';
const TOAST_TITLE = '🎬 Видео';

const POLL_MS = 5000;
const MAX_TEXT_CHARS = 1500;
const MAX_POLL_ERRORS = 6;
const DONE_STATUS_TTL_MS = 15000;

const DELIVER = ['chat', 'tg', 'both'];
const RESOLUTIONS = [480, 720];
const QUALITIES = ['fast', 'hi'];
const MAX_COUNT = 3;
const ERROR_STATUS_TTL_MS = 5 * 60 * 1000;
/** 🔗: seam between clips — hard cut or a short dissolve (seconds, sent as `xfade`). */
const XFADE_OPTIONS = [
    { value: 0, label: 'встык' },
    { value: 0.25, label: 'плавно, 0.25 с' },
    { value: 0.5, label: 'плавно, 0.5 с' },
];

export const DEFAULT_SYSTEM_PROMPT = [
    'You turn one frame of an adult anime roleplay (all characters are adults, fictional, consenting) into a prompt for the Wan 2.2 image-to-video model.',
    'Wan reads natural English sentences, not tags. The frame already fixes who is there and where; your job is the MOTION of the next few seconds.',
    'Output JSON only: {"lora": ["set", ...], "prompt": "..."}',
    'lora: the names of the LoRA sets from the list at the end of this prompt that fit the frame (several allowed, [] if none): the explicit set when the frame shows an explicit sex act, the nsfw set for nudity or sensual touching, nothing otherwise.',
    'The prompt is ONE paragraph of 60-100 words, present tense, third person, built in this order:',
    '1. Only if a chosen set has trigger words: the single trigger word for the position comes first, taken from that set\'s trigger list.',
    '2. "Anime style," plus 3-5 words on the look of the frame (soft painterly 2D illustration, warm palette, clean lines...).',
    '3. One sentence with the people named by what is visible, never by name: "the silver-haired man", "the blonde woman", their pose, clothing or nudity, exactly as in the frame.',
    '4. The main motion: ONE continuous action with simple direct verbs (strokes, bobs, thrusts, leans, breathes), how it repeats or continues and its rhythm (slow, steady, rhythmic). Then 1-2 secondary motions: hair sways, chest rises, cloth shifts, steam drifts, light flickers.',
    '5. Camera and light: "static shot", the shot size that matches the frame (close-up, medium close-up, medium shot, wide shot), the lighting (soft morning light, warm lamp light, dim room...).',
    '6. Finish with "smooth continuous motion, high quality".',
    'Rules: describe only what can move from this exact frame; no new characters, no scene change, no cuts, no "then" or "after"; no negations (never write "no", "without", "not"); no tag lists; the image-model tags you get are for reference only, do not copy them; be literal and explicit when the frame is explicit; no disclaimers.',
    'Example: {"lora": [], "prompt": "Anime style, soft painterly illustration with a warm palette. The silver-haired man leans over the sleeping blonde woman in bed and slowly strokes her hair, his hand moving in gentle repeated passes from her temple to the pillow. Her chest rises and falls with slow breathing, her lips part slightly, loose strands of hair shift under his fingers. Static shot, medium close-up, soft overcast morning light from the window. Smooth continuous motion, high quality."}',
].join('\n');
// earlier releases: v1 asked for character names via {NAMES}, v2 wrote two-line FRAME/VIDEO-ish prompts, v3 and the first
// catalogue-aware prompt hard-coded the LoRA names; saved copies of those are migrated to the current default
const LEGACY_PROMPT_MARKERS = [
    'Use these English names for the characters: {NAMES}',
    'Never use character names: say "the man"',
    '{"lora": "none|nsfw|dreamlay"',
    'lists the names of the LoRA sets from the list below',
];

const DEFAULTS = Object.freeze({
    bridgeUrl: '/comfy-bridge',
    bridgeKey: '',
    profileId: '',
    direct: false,
    sec: 5,
    res: 480,
    quality: 'fast',
    smooth: false,
    count: 1,
    negExtra: '',
    deliver: 'chat',
    xfade: 0,
    systemPrompt: DEFAULT_SYSTEM_PROMPT,
    maxTokens: 800,
});

const MEDIA_VIDEO = MEDIA_TYPE?.VIDEO ?? 'video';

// ---------------------------------------------------------------------------
// Settings
// ---------------------------------------------------------------------------

function getSettings() {
    if (!extension_settings[MODULE] || typeof extension_settings[MODULE] !== 'object') {
        extension_settings[MODULE] = {};
    }
    const settings = extension_settings[MODULE];
    for (const [key, value] of Object.entries(DEFAULTS)) {
        if (settings[key] === undefined || settings[key] === null) {
            settings[key] = value;
        }
    }
    if (LEGACY_PROMPT_MARKERS.some(marker => String(settings.systemPrompt || '').includes(marker))) {
        settings.systemPrompt = DEFAULT_SYSTEM_PROMPT;
    }
    delete settings.lora;
    delete settings.loraStrength;
    delete settings.names;
    return settings;
}

const SETTINGS_HTML = `
<div id="tavern_video_settings" class="tavern-video-settings">
    <div class="inline-drawer">
        <div class="inline-drawer-toggle inline-drawer-header">
            <b>🎬 Видео</b>
            <div class="inline-drawer-icon fa-solid fa-circle-chevron-down down"></div>
        </div>
        <div class="inline-drawer-content">
            <div class="tv-section">
                <h4><i class="fa-solid fa-plug"></i> Мост</h4>
                <div class="tv-row"><label for="tv_bridge_url">Адрес</label><input id="tv_bridge_url" class="text_pole" type="text" placeholder="/comfy-bridge" autocomplete="off"></div>
                <div class="tv-row"><label for="tv_bridge_key">Ключ</label><input id="tv_bridge_key" class="text_pole" type="password" placeholder="пусто = ключ из SLAY" autocomplete="new-password"><div id="tv_key_toggle" class="menu_button tv-key-toggle" title="Показать / скрыть"><i class="fa-solid fa-eye"></i></div></div>
                <div class="tv-row"><label for="tv_profile">Профиль</label><select id="tv_profile" class="text_pole"></select></div>
                <p class="tv-hint">Профиль Connection Manager с моделью, которая видит картинки (Gemini Flash подходит).</p>
                <label class="checkbox_label tv-check" for="tv_direct"><input id="tv_direct" type="checkbox"><span>Слать запрос напрямую (если через профиль модель не видит картинку)</span></label>
                <div id="tv_test" class="menu_button tv-test"><i class="fa-solid fa-wifi"></i> Тест</div>
            </div>
            <div class="tv-section">
                <h4><i class="fa-solid fa-sliders"></i> Параметры видео</h4>
                <div class="tv-row"><label for="tv_sec">Секунды</label><input id="tv_sec" class="text_pole" type="number" min="1" max="10" step="1"></div>
                <div class="tv-row"><label for="tv_res">Разрешение</label><select id="tv_res" class="text_pole"><option value="480">480p</option><option value="720">720p</option></select></div>
                <div class="tv-row"><label for="tv_quality">Качество</label><select id="tv_quality" class="text_pole"><option value="fast">быстро</option><option value="hi">лучше</option></select></div>
                <div class="tv-row"><label for="tv_count">Роликов</label><input id="tv_count" class="text_pole" type="number" min="1" max="3" step="1"></div>
                <label class="checkbox_label tv-check" for="tv_smooth"><input id="tv_smooth" type="checkbox"><span>32 fps (интерполяция)</span></label>
                <div class="tv-row"><label for="tv_neg_extra">Негатив</label><input id="tv_neg_extra" class="text_pole" type="text" placeholder="что не должно появиться (neg_extra)" autocomplete="off"></div>
                <div class="tv-row"><label for="tv_deliver">Куда</label><select id="tv_deliver" class="text_pole"><option value="chat">чат</option><option value="tg">телеграм</option><option value="both">оба</option></select></div>
                <p class="tv-hint">Это значения по умолчанию для попапа — там всё можно поменять. LoRA-сеты модель выбирает сама по кадру из каталога ниже.</p>
            </div>
            <div class="tv-section">
                <h4><i class="fa-solid fa-layer-group"></i> Каталог LoRA <div id="tv_lora_refresh" class="menu_button tv-reset" title="Перечитать каталог с моста"><i class="fa-solid fa-rotate"></i> обновить</div></h4>
                <div id="tv_lora_catalog" class="tv-catalog tv-hint">каталог ещё не загружен</div>
            </div>
            <div class="tv-section">
                <h4><i class="fa-solid fa-brain"></i> Промпт для модели <div id="tv_sysprompt_reset" class="menu_button tv-reset" title="Вернуть промпт по умолчанию"><i class="fa-solid fa-rotate-left"></i> сброс</div></h4>
                <textarea id="tv_sysprompt" class="text_pole" rows="8"></textarea>
                <p class="tv-hint">В конец промпта автоматически добавляется список LoRA-сетов с моста (Available LoRA sets: …).</p>
            </div>
        </div>
    </div>
</div>`;

function populateProfiles() {
    const select = document.getElementById('tv_profile');
    if (!select) return;
    const settings = getSettings();
    const profiles = getContext().extensionSettings?.connectionManager?.profiles ?? [];

    select.innerHTML = '';
    select.add(new Option('— выбери профиль —', ''));
    for (const profile of profiles) {
        const details = [profile.api, profile.model].filter(Boolean).join(', ');
        const label = details ? `${profile.name} (${details})` : profile.name;
        select.add(new Option(label, profile.id));
    }
    select.value = profiles.some(p => p.id === settings.profileId) ? settings.profileId : '';
}

function bindSettingsUi() {
    const settings = getSettings();
    const container = document.getElementById('extensions_settings2') || document.getElementById('extensions_settings');
    if (!container) {
        console.warn(LOG, 'Settings container not found');
        return;
    }
    container.insertAdjacentHTML('beforeend', SETTINGS_HTML);

    const $url = $('#tv_bridge_url').val(settings.bridgeUrl);
    const $key = $('#tv_bridge_key').val(settings.bridgeKey);
    const $direct = $('#tv_direct').prop('checked', !!settings.direct);
    const $sec = $('#tv_sec').val(settings.sec);
    const $res = $('#tv_res').val(String(settings.res));
    const $quality = $('#tv_quality').val(settings.quality);
    const $count = $('#tv_count').val(settings.count);
    const $smooth = $('#tv_smooth').prop('checked', !!settings.smooth);
    const $negExtra = $('#tv_neg_extra').val(settings.negExtra);
    const $deliver = $('#tv_deliver').val(settings.deliver);
    const $sysprompt = $('#tv_sysprompt').val(settings.systemPrompt);
    populateProfiles();

    const save = () => saveSettingsDebounced();

    $url.on('input', () => { settings.bridgeUrl = String($url.val()).trim(); save(); });
    $key.on('input', () => { settings.bridgeKey = String($key.val()).trim(); save(); });
    $direct.on('change', () => { settings.direct = $direct.prop('checked'); save(); });
    $('#tv_profile').on('change', function () { settings.profileId = String($(this).val() || ''); save(); });
    $sec.on('input', () => { settings.sec = clampInt($sec.val(), 1, 10, DEFAULTS.sec); save(); });
    $res.on('change', () => { settings.res = RESOLUTIONS.includes(Number($res.val())) ? Number($res.val()) : DEFAULTS.res; save(); });
    $quality.on('change', () => { settings.quality = QUALITIES.includes(String($quality.val())) ? String($quality.val()) : 'fast'; save(); });
    $count.on('input', () => { settings.count = clampInt($count.val(), 1, MAX_COUNT, 1); save(); });
    $smooth.on('change', () => { settings.smooth = $smooth.prop('checked'); save(); });
    $negExtra.on('input', () => { settings.negExtra = String($negExtra.val()).trim(); save(); });
    $deliver.on('change', () => { settings.deliver = DELIVER.includes(String($deliver.val())) ? String($deliver.val()) : 'chat'; save(); });
    $sysprompt.on('input', () => { settings.systemPrompt = String($sysprompt.val()); save(); });
    $('#tv_key_toggle').on('click', () => {
        const show = $key.attr('type') === 'password';
        $key.attr('type', show ? 'text' : 'password');
        $('#tv_key_toggle i').toggleClass('fa-eye', !show).toggleClass('fa-eye-slash', show);
    });
    $('#tv_test').on('click', async function () {
        const $btn = $(this);
        if ($btn.hasClass('testing')) return;
        $btn.addClass('testing');
        try {
            const r = await bridgeFetchJson('/', { method: 'GET' });
            if (r?.ok) toastr.success(`Мост на связи · ComfyUI ${r.comfy || '?'}`, TOAST_TITLE);
            else toastr.warning(`Мост отвечает, но ComfyUI ${r?.comfy || 'не отвечает'}`, TOAST_TITLE);
        } catch (error) {
            toastr.error(String(error?.message || error), TOAST_TITLE);
        } finally {
            $btn.removeClass('testing');
        }
    });
    $('#tv_sysprompt_reset').on('click', () => {
        settings.systemPrompt = DEFAULT_SYSTEM_PROMPT;
        $sysprompt.val(DEFAULT_SYSTEM_PROMPT);
        save();
        toastr.info('Системный промпт сброшен', TOAST_TITLE);
    });

    for (const name of ['CONNECTION_PROFILE_CREATED', 'CONNECTION_PROFILE_UPDATED', 'CONNECTION_PROFILE_DELETED']) {
        if (event_types[name]) {
            eventSource.on(event_types[name], () => populateProfiles());
        }
    }
    // Profiles may load after us (loading order) — refresh once the app is ready and when the drawer opens.
    if (event_types.APP_READY) {
        eventSource.on(event_types.APP_READY, () => populateProfiles());
    }
    $('#tavern_video_settings .inline-drawer-toggle').on('click', () => {
        populateProfiles();
        // Settings open → refresh the LoRA catalogue from the bridge.
        refreshLoraCatalog({ force: true });
    });
    $('#tv_lora_refresh').on('click', () => refreshLoraCatalog({ force: true, notify: true }));
    renderLoraCatalog();
}

// ---------------------------------------------------------------------------
// LoRA catalogue (GET {bridgeUrl}/video/loras) — cached per page load
// ---------------------------------------------------------------------------

/**
 * @typedef {object} LoraSet
 * @property {string} name
 * @property {string[]} triggers
 * @property {string} hint
 * @property {number} strength
 * @property {string} group
 */

/** @type {{ loras: LoraSet[], fetchedAt: number, error: string|null, promise: Promise<LoraSet[]>|null }} */
const loraCatalog = { loras: [], fetchedAt: 0, error: null, promise: null };

function normalizeLoraSet(raw) {
    if (!raw || typeof raw !== 'object') return null;
    const name = String(raw.name ?? '').trim();
    if (!name) return null;
    const triggers = Array.isArray(raw.triggers)
        ? raw.triggers.map(t => String(t).trim()).filter(Boolean)
        : String(raw.triggers ?? '').split(',').map(t => t.trim()).filter(Boolean);
    return {
        name,
        triggers,
        hint: String(raw.hint ?? '').trim(),
        strength: clampFloat(raw.strength, 0, 2, 1.0),
        group: String(raw.group ?? '').trim(),
    };
}

/**
 * Loads the catalogue once per page load; `force` re-fetches (settings opened / refresh button).
 * Never throws: on failure the previous catalogue (or an empty one) is kept and `loraCatalog.error` is set.
 * @returns {Promise<LoraSet[]>}
 */
async function fetchLoraCatalog({ force = false } = {}) {
    if (!force && loraCatalog.fetchedAt) return loraCatalog.loras;
    if (loraCatalog.promise) return loraCatalog.promise;
    loraCatalog.promise = (async () => {
        try {
            const json = await bridgeFetchJson('/video/loras', { method: 'GET' });
            const list = Array.isArray(json?.loras) ? json.loras : [];
            loraCatalog.loras = list.map(normalizeLoraSet).filter(Boolean);
            loraCatalog.fetchedAt = Date.now();
            loraCatalog.error = null;
            console.info(LOG, `LoRA catalogue: ${loraCatalog.loras.length} set(s)`);
        } catch (error) {
            loraCatalog.error = String(error?.message || error);
            console.warn(LOG, 'LoRA catalogue fetch failed', error);
        } finally {
            loraCatalog.promise = null;
        }
        return loraCatalog.loras;
    })();
    return loraCatalog.promise;
}

async function refreshLoraCatalog({ force = false, notify = false } = {}) {
    const el = document.getElementById('tv_lora_catalog');
    if (el && (force || !loraCatalog.fetchedAt)) el.textContent = 'загружаю каталог…';
    await fetchLoraCatalog({ force });
    renderLoraCatalog();
    if (notify) {
        if (loraCatalog.error) toastr.error(`Каталог LoRA: ${loraCatalog.error}`, TOAST_TITLE);
        else toastr.info(`Каталог LoRA: ${loraCatalog.loras.length} сет(ов)`, TOAST_TITLE);
    }
}

function renderLoraCatalog() {
    const el = document.getElementById('tv_lora_catalog');
    if (!el) return;
    el.innerHTML = '';
    if (loraCatalog.error && !loraCatalog.loras.length) {
        el.textContent = `не удалось загрузить: ${loraCatalog.error}`;
        return;
    }
    if (!loraCatalog.fetchedAt) {
        el.textContent = 'каталог ещё не загружен';
        return;
    }
    if (!loraCatalog.loras.length) {
        el.textContent = 'бридж не вернул ни одного LoRA-сета';
        return;
    }
    for (const set of loraCatalog.loras) {
        const row = document.createElement('div');
        row.className = 'tv-catalog-row';
        const meta = [set.group, set.triggers.length ? `триггеры: ${set.triggers.join(', ')}` : '', `сила ${formatStrength(set.strength)}`].filter(Boolean).join(' · ');
        row.innerHTML = `<b>${escapeHtml(set.name)}</b> <span>${escapeHtml(meta)}</span>${set.hint ? `<div class="tv-catalog-hint">${escapeHtml(set.hint)}</div>` : ''}`;
        el.appendChild(row);
    }
    if (loraCatalog.error) {
        const warn = document.createElement('div');
        warn.textContent = `(последнее обновление не удалось: ${loraCatalog.error})`;
        el.appendChild(warn);
    }
}

/** Text block appended to the system prompt. */
function loraCatalogPromptBlock() {
    if (!loraCatalog.loras.length) {
        return 'Available LoRA sets: none (answer "lora": []).';
    }
    const lines = loraCatalog.loras.map(set => {
        const triggers = set.triggers.length ? set.triggers.join(', ') : '(no trigger words)';
        return `- ${set.name} — ${triggers} — ${set.hint || '(no hint)'}`;
    });
    return ['Available LoRA sets:', ...lines].join('\n');
}

/**
 * Accepts "name", "a, b", ["a", "b"], "none"; returns catalogue sets that exist (unknown names ignored).
 * @returns {LoraSet[]}
 */
function resolveLoraNames(value) {
    let names = [];
    if (Array.isArray(value)) names = value.map(v => String(v ?? ''));
    else if (typeof value === 'string') names = value.split(/[,;\n]+/);
    else if (value && typeof value === 'object' && typeof value.name === 'string') names = [value.name];
    const wanted = names.map(n => n.trim().toLowerCase()).filter(n => n && n !== 'none');
    const result = [];
    for (const name of wanted) {
        const set = loraCatalog.loras.find(s => s.name.toLowerCase() === name);
        if (set && !result.includes(set)) result.push(set);
    }
    return result;
}

// ---------------------------------------------------------------------------
// Small helpers
// ---------------------------------------------------------------------------

function clampInt(value, min, max, fallback) {
    const n = parseInt(String(value), 10);
    if (!Number.isFinite(n)) return fallback;
    return Math.min(max, Math.max(min, n));
}

function clampFloat(value, min, max, fallback) {
    const n = parseFloat(String(value));
    if (!Number.isFinite(n)) return fallback;
    return Math.min(max, Math.max(min, Math.round(n * 100) / 100));
}

function debounce(fn, ms) {
    let timer = null;
    return (...args) => {
        clearTimeout(timer);
        timer = setTimeout(() => fn(...args), ms);
    };
}

function stripHtml(html) {
    try {
        const doc = new DOMParser().parseFromString(String(html ?? ''), 'text/html');
        return (doc.body?.textContent ?? '').replace(/[ \t]+\n/g, '\n').replace(/\n{3,}/g, '\n\n').trim();
    } catch {
        return String(html ?? '').replace(/<[^>]*>/g, '').trim();
    }
}

function blobToDataUrl(blob) {
    return new Promise((resolve, reject) => {
        const reader = new FileReader();
        reader.onload = () => resolve(String(reader.result));
        reader.onerror = () => reject(reader.error ?? new Error('FileReader failed'));
        reader.readAsDataURL(blob);
    });
}

function isAbsoluteUrl(url) {
    return /^https?:\/\//i.test(url);
}

function bridgeUrl(path) {
    const base = String(getSettings().bridgeUrl || DEFAULTS.bridgeUrl).trim().replace(/\/+$/, '');
    return base + (path.startsWith('/') ? path : `/${path}`);
}

/**
 * Resolves `video_url` from the bridge: absolute URLs are used as-is, paths are
 * appended to the bridge URL (unless they already start with the bridge path).
 */
function resolveBridgeFileUrl(url) {
    const value = String(url || '').trim();
    if (!value) throw new Error('Бридж не вернул video_url');
    if (isAbsoluteUrl(value) || value.startsWith('data:') || value.startsWith('blob:')) return value;
    const base = String(getSettings().bridgeUrl || DEFAULTS.bridgeUrl).trim().replace(/\/+$/, '');
    const basePath = isAbsoluteUrl(base) ? new URL(base).pathname.replace(/\/+$/, '') : base;
    if (basePath && value.startsWith(`${basePath}/`)) {
        return isAbsoluteUrl(base) ? new URL(value, base).href : value;
    }
    return bridgeUrl(value);
}

/**
 * Bridge key: the extension's own setting, or — when it is empty — the key SLAY Images
 * already uses for the same comfy-bridge endpoint (so the tavern needs it typed in once).
 */
function effectiveBridgeKey() {
    const own = String(getSettings().bridgeKey || '').trim();
    if (own) return own;
    const slay = extension_settings?.slay_image_gen;
    // SLAY stores the endpoint without a leading slash ("comfy-bridge/v1/chat/completions"), compare path-insensitively
    const norm = (v) => String(v || '').trim().replace(/^https?:\/\/[^/]+/i, '').replace(/^\/+|\/+$/g, '').toLowerCase();
    const base = norm(getSettings().bridgeUrl || DEFAULTS.bridgeUrl);
    if (slay?.apiKey && base && norm(slay.endpoint).startsWith(base)) return String(slay.apiKey).trim();
    return '';
}

function bridgeHeaders(extra = {}) {
    const key = effectiveBridgeKey();
    const headers = { ...extra };
    if (key) headers['Authorization'] = `Bearer ${key}`;
    return headers;
}

async function bridgeFetchJson(path, init = {}) {
    const response = await fetch(bridgeUrl(path), {
        ...init,
        headers: bridgeHeaders({ 'Content-Type': 'application/json', ...(init.headers || {}) }),
    });
    const text = await response.text();
    let json = null;
    try { json = text ? JSON.parse(text) : null; } catch { /* not json */ }
    if (!response.ok) {
        const detail = json?.error || json?.detail || text.slice(0, 200) || response.statusText;
        throw new Error(`бридж ответил ${response.status}: ${detail}`);
    }
    if (json === null) throw new Error('бридж вернул не-JSON');
    return json;
}

function formatElapsed(seconds) {
    const total = Math.max(0, Math.floor(Number(seconds) || 0));
    const m = Math.floor(total / 60);
    const s = total % 60;
    return `${m}:${String(s).padStart(2, '0')}`;
}

// ---------------------------------------------------------------------------
// Image → base64 (original resolution)
// ---------------------------------------------------------------------------

function canvasToBase64(img) {
    const canvas = document.createElement('canvas');
    canvas.width = img.naturalWidth || img.width;
    canvas.height = img.naturalHeight || img.height;
    if (!canvas.width || !canvas.height) throw new Error('картинка ещё не загрузилась');
    canvas.getContext('2d').drawImage(img, 0, 0);
    const dataUrl = canvas.toDataURL('image/png');
    return { base64: dataUrl.split(',')[1], mime: 'image/png' };
}

async function imageToBase64(img) {
    const src = img.currentSrc || img.src;
    if (!src) throw new Error('у картинки нет src');
    try {
        const response = await fetch(src);
        if (!response.ok) throw new Error(`HTTP ${response.status}`);
        const blob = await response.blob();
        const mime = (blob.type || '').split(';')[0].trim().toLowerCase();
        if (mime === 'image/png' || mime === 'image/jpeg') {
            const dataUrl = await blobToDataUrl(blob);
            return { base64: dataUrl.split(',')[1], mime };
        }
        // webp/gif/unknown → re-encode to PNG at the same resolution.
        if (img.complete && img.naturalWidth) {
            return canvasToBase64(img);
        }
        const bitmap = await createImageBitmap(blob);
        const canvas = document.createElement('canvas');
        canvas.width = bitmap.width;
        canvas.height = bitmap.height;
        canvas.getContext('2d').drawImage(bitmap, 0, 0);
        return { base64: canvas.toDataURL('image/png').split(',')[1], mime: 'image/png' };
    } catch (error) {
        console.warn(LOG, 'fetch(image) failed, falling back to canvas', error);
        return canvasToBase64(img);
    }
}

// ---------------------------------------------------------------------------
// Vision model → {lora, prompt}
// ---------------------------------------------------------------------------

function getProfile(profileId) {
    const profiles = getContext().extensionSettings?.connectionManager?.profiles ?? [];
    return profiles.find(p => p.id === profileId) ?? null;
}

function buildMessages({ base64, mime, instruction, text, continueFrom = null }) {
    const settings = getSettings();
    const systemPrompt = String(settings.systemPrompt || DEFAULT_SYSTEM_PROMPT).replace(/\{NAMES\}/g, 'the man and the woman')
        + '\n\n' + loraCatalogPromptBlock();
    const lines = [];
    if (continueFrom !== null) {
        lines.push('Continue the motion from this frame, it is the last frame of the previous clip.');
        if (continueFrom) lines.push(`Previous clip prompt: ${continueFrom}`);
        lines.push('');
    }
    lines.push(
        `Image-model tags (reference only): ${instruction || '(none)'}`,
        '',
        'Scene text:',
        text || '(empty)',
    );
    const userText = lines.join('\n');
    return [
        { role: 'system', content: systemPrompt },
        {
            role: 'user',
            content: [
                { type: 'text', text: userText },
                { type: 'image_url', image_url: { url: `data:${mime};base64,${base64}`, detail: 'auto' } },
            ],
        },
    ];
}

/**
 * Direct request to ST's chat-completions backend (bypasses Connection Manager),
 * used when the profile is not a chat-completion profile, when the CM path failed
 * or when the user enabled "direct" in settings.
 */
async function directVisionRequest(profile, messages) {
    const context = getContext();
    const settings = getSettings();
    const apiMap = context.CONNECT_API_MAP?.[profile.api];
    const source = apiMap?.source || 'custom';
    const proxyPreset = Array.isArray(proxies) ? proxies.find(p => p.name === profile.proxy) : null;
    const oai = context.chatCompletionSettings || {};
    // ST 1.19 runs the custom include/exclude fields through substituteParams before sending
    // (public/scripts/openai.js); mirror that so the direct path sees the same headers/body.
    const macros = (value) => (typeof substituteParams === 'function' && typeof value === 'string' && value) ? substituteParams(value) : value;

    const body = {
        stream: false,
        messages,
        model: profile.model,
        chat_completion_source: source,
        custom_url: profile['api-url'] || (source === 'custom' ? oai.custom_url : undefined),
        secret_id: profile['secret-id'],
        reverse_proxy: proxyPreset?.url,
        proxy_password: proxyPreset?.password,
        custom_include_body: macros(oai.custom_include_body),
        custom_exclude_body: macros(oai.custom_exclude_body),
        custom_include_headers: macros(oai.custom_include_headers),
        custom_prompt_post_processing: profile['prompt-post-processing'] || undefined,
        max_tokens: settings.maxTokens,
        temperature: 0.7,
        use_sysprompt: true,
    };
    for (const key of Object.keys(body)) {
        if (body[key] === undefined || body[key] === '') delete body[key];
    }

    const response = await fetch('/api/backends/chat-completions/generate', {
        method: 'POST',
        headers: getRequestHeaders(),
        cache: 'no-cache',
        body: JSON.stringify(body),
    });
    const json = await response.json().catch(() => ({}));
    if (!response.ok || json?.error) {
        throw new Error(String(json?.error?.message || json?.error || `HTTP ${response.status}`));
    }
    const content = json?.choices?.[0]?.message?.content
        ?? json?.choices?.[0]?.text
        ?? (Array.isArray(json?.content) ? json.content.filter(p => p.type === 'text').map(p => p.text).join('\n') : json?.content)
        ?? json?.text
        ?? '';
    return typeof content === 'string' ? content : JSON.stringify(content);
}

function isChatCompletionProfile(profile) {
    try {
        return ConnectionManagerRequestService.isProfileSupported(profile)
            && getContext().CONNECT_API_MAP?.[profile.api]?.selected === 'openai';
    } catch {
        return false;
    }
}

/**
 * @returns {{ loras: LoraSet[], prompt: string }}
 */
function parseModelJson(raw) {
    let text = String(raw ?? '').trim();
    text = text.replace(/^```(?:json)?\s*/i, '').replace(/```\s*$/, '').trim();
    const start = text.indexOf('{');
    const end = text.lastIndexOf('}');
    if (start !== -1 && end > start) {
        try {
            const obj = JSON.parse(text.slice(start, end + 1));
            const loras = resolveLoraNames(obj.lora ?? obj.loras);
            const prompt = String(obj.prompt ?? '').trim();
            if (prompt) return { loras, prompt };
        } catch (error) {
            console.warn(LOG, 'model JSON parse failed', error, text);
        }
    }
    if (!text) throw new Error('модель вернула пустой ответ');
    return { loras: [], prompt: text };
}

async function askVisionModel(payload) {
    const settings = getSettings();
    if (!settings.profileId) throw new Error('выбери профиль подключения в настройках «🎬 Видео»');
    const profile = getProfile(settings.profileId);
    if (!profile) throw new Error('профиль подключения не найден — выбери другой в настройках');

    const messages = buildMessages(payload);
    let raw;
    if (!settings.direct && isChatCompletionProfile(profile)) {
        try {
            const result = await ConnectionManagerRequestService.sendRequest(
                settings.profileId,
                messages,
                settings.maxTokens,
                { stream: false, extractData: true, includePreset: true, includeInstruct: false },
            );
            raw = typeof result === 'string' ? result : result?.content;
        } catch (error) {
            console.warn(LOG, 'Connection Manager request failed, trying direct request', error);
            raw = await directVisionRequest(profile, messages);
        }
    } else {
        raw = await directVisionRequest(profile, messages);
    }
    console.debug(LOG, 'model answer:', raw);
    return parseModelJson(raw);
}

// ---------------------------------------------------------------------------
// Popup
// ---------------------------------------------------------------------------

function escapeHtml(text) {
    return String(text ?? '')
        .replace(/&/g, '&amp;')
        .replace(/</g, '&lt;')
        .replace(/>/g, '&gt;')
        .replace(/"/g, '&quot;');
}

/** 1 → "1.0", 0.85 → "0.85" (what the bridge expects in "set:strength"). */
function formatStrength(value) {
    const rounded = Math.round(Number(value) * 100) / 100;
    return Number.isInteger(rounded) ? rounded.toFixed(1) : String(rounded);
}

function renderLoraChecklist(selected) {
    if (!loraCatalog.loras.length) {
        const reason = loraCatalog.error ? `каталог LoRA недоступен (${escapeHtml(loraCatalog.error)})` : 'бридж не вернул ни одного LoRA-сета';
        return `<div class="tv-lora-empty tv-hint">${reason}</div>`;
    }
    return loraCatalog.loras.map((set, index) => {
        const checked = selected.some(s => s.name === set.name) ? ' checked' : '';
        const triggers = set.triggers.length ? set.triggers.join(', ') : '—';
        const group = set.group ? ` <span class="tv-lora-group">${escapeHtml(set.group)}</span>` : '';
        return `
        <div class="tv-lora-row" title="${escapeHtml(set.hint)}">
            <label class="tv-lora-pick">
                <input type="checkbox" class="tv-lora-check" data-index="${index}" value="${escapeHtml(set.name)}"${checked}>
                <b>${escapeHtml(set.name)}</b>${group}
                <span class="tv-lora-triggers">${escapeHtml(triggers)}</span>
            </label>
            <input type="number" class="text_pole tv-lora-strength" data-index="${index}" min="0" max="2" step="0.05" value="${escapeHtml(formatStrength(set.strength))}" title="Сила">
        </div>`;
    }).join('');
}

async function showJobPopup({ prompt, loras = [], previewSrc, title = '🎬 Видео' }) {
    const settings = getSettings();
    const resOptions = RESOLUTIONS.map(v => `<option value="${v}"${v === Number(settings.res) ? ' selected' : ''}>${v}</option>`).join('');
    const qualityLabels = { fast: 'быстро', hi: 'лучше' };
    const qualityOptions = QUALITIES.map(v => `<option value="${v}"${v === settings.quality ? ' selected' : ''}>${qualityLabels[v]}</option>`).join('');
    const deliverLabels = { chat: 'чат', tg: 'телеграм', both: 'оба' };
    const deliverRadios = DELIVER.map(v => `<label><input type="radio" name="tv_p_deliver" value="${v}"${v === settings.deliver ? ' checked' : ''}> ${deliverLabels[v]}</label>`).join('');

    const wrapper = document.createElement('div');
    wrapper.className = 'tv-popup';
    wrapper.innerHTML = `
        <h3>${escapeHtml(title)}</h3>
        ${previewSrc ? `<div class="tv-preview"><img src="${escapeHtml(previewSrc)}" alt=""></div>` : ''}
        <label for="tv_p_prompt">Промпт</label>
        <textarea id="tv_p_prompt" class="text_pole" rows="7"></textarea>
        <div class="tv-lora-head"><span>LoRA</span><span class="tv-hint">галочка = сет уходит в рендер, число = сила</span></div>
        <div class="tv-lora-list">${renderLoraChecklist(loras)}</div>
        <div class="tv-grid">
            <label>Секунды <input id="tv_p_sec" class="text_pole" type="number" min="1" max="10" step="1" value="${escapeHtml(settings.sec)}"></label>
            <label>Разрешение <select id="tv_p_res" class="text_pole">${resOptions}</select></label>
            <label>Seed <input id="tv_p_seed" class="text_pole" type="number" step="1" placeholder="случайный"></label>
            <label>Качество <select id="tv_p_quality" class="text_pole">${qualityOptions}</select></label>
            <label>Роликов <input id="tv_p_count" class="text_pole" type="number" min="1" max="${MAX_COUNT}" step="1" value="${escapeHtml(settings.count)}"></label>
        </div>
        <label class="tv-field"><span>Негатив (дополнительно)</span><input id="tv_p_neg" class="text_pole" type="text" placeholder="что не должно появиться" value="${escapeHtml(settings.negExtra)}"></label>
        <div class="tv-radios">
            <label><input type="checkbox" id="tv_p_smooth"${settings.smooth ? ' checked' : ''}> 32 fps</label>
            <span class="tv-radios-sep"></span>
            <span>Куда:</span>${deliverRadios}
        </div>`;
    wrapper.querySelector('#tv_p_prompt').value = prompt;

    let captured = null;
    const capture = () => {
        const seedRaw = String(wrapper.querySelector('#tv_p_seed').value || '').trim();
        const pickedLoras = [];
        for (const check of wrapper.querySelectorAll('.tv-lora-check:checked')) {
            const set = loraCatalog.loras[Number(check.dataset.index)];
            if (!set) continue;
            const strengthInput = wrapper.querySelector(`.tv-lora-strength[data-index="${check.dataset.index}"]`);
            pickedLoras.push({ name: set.name, strength: clampFloat(strengthInput?.value, 0, 2, set.strength) });
        }
        captured = {
            prompt: String(wrapper.querySelector('#tv_p_prompt').value || '').trim(),
            loras: pickedLoras,
            sec: clampInt(wrapper.querySelector('#tv_p_sec').value, 1, 10, settings.sec),
            res: clampInt(wrapper.querySelector('#tv_p_res').value, 1, 4096, settings.res),
            seed: seedRaw === '' ? null : clampInt(seedRaw, -2147483648, 4294967295, null),
            quality: QUALITIES.includes(wrapper.querySelector('#tv_p_quality').value) ? wrapper.querySelector('#tv_p_quality').value : 'fast',
            smooth: !!wrapper.querySelector('#tv_p_smooth').checked,
            count: clampInt(wrapper.querySelector('#tv_p_count').value, 1, MAX_COUNT, 1),
            negExtra: String(wrapper.querySelector('#tv_p_neg').value || '').trim(),
            deliver: wrapper.querySelector('input[name="tv_p_deliver"]:checked')?.value || settings.deliver,
        };
    };

    const result = await callGenericPopup(wrapper, POPUP_TYPE.CONFIRM, '', {
        okButton: 'Го',
        cancelButton: 'Отмена',
        wide: true,
        allowVerticalScrolling: true,
        onClosing: (popup) => {
            if (popup.result === POPUP_RESULT.AFFIRMATIVE) {
                capture();
                if (!captured.prompt) {
                    toastr.warning('Промпт пустой', TOAST_TITLE);
                    return false;
                }
            }
            return true;
        },
    });

    if (result !== POPUP_RESULT.AFFIRMATIVE || !captured) return null;
    return captured;
}

// ---------------------------------------------------------------------------
// Jobs: create, poll, attach
// ---------------------------------------------------------------------------

/**
 * @typedef {object} JobState
 * @property {string} id
 * @property {string} key
 * @property {string} chatId
 * @property {number} mesId
 * @property {string} src        Source image src (where the status line lives)
 * @property {number} n          Display number within the message (1-based)
 * @property {string} deliver
 * @property {string} prompt
 * @property {string} icon
 * @property {string} label
 * @property {boolean} error
 * @property {number} errors
 * @property {any} timer
 * @property {boolean} finished
 * @property {number} until      recent-only: when to drop the entry from the status line
 * @property {number} position   queue position (queued only)
 */

/** @type {Map<string, JobState>} active (polling) jobs */
const jobs = new Map();
/** @type {Map<string, JobState>} finished jobs still shown in the status line */
const recentJobs = new Map();
/** @type {Map<string, Array<{mesId:number, path:string, title:string, jobId:string}>>} */
const pendingAttach = new Map();

function jobKey(chatId, mesId, jobId) {
    return `${chatId}::${mesId}::${jobId}`;
}

function currentChatId() {
    const context = getContext();
    return String(context.chatId ?? context.getCurrentChatId?.() ?? '');
}

function findImageWrap(mesId, src) {
    const mesEl = document.querySelector(`#chat .mes[mesid="${mesId}"]`);
    if (!mesEl) return null;
    const images = mesEl.querySelectorAll('.mes_text img[data-iig-instruction]');
    const img = Array.from(images).find(i => i.getAttribute('src') === src)
        ?? (images.length === 1 ? images[0] : null);
    if (img) return getWrap(img);
    // Image gone (message edited) — put the status right under the message text instead.
    return mesEl.querySelector('.mes_text');
}

function renderStatus(wrap, text, { error = false } = {}) {
    if (!wrap) return;
    let el = wrap.nextElementSibling;
    if (!(el && el.classList && el.classList.contains('tv-status'))) el = null;
    if (!text) {
        el?.remove();
        return;
    }
    if (!el) {
        el = document.createElement('div');
        el.className = 'tv-status';
        wrap.insertAdjacentElement('afterend', el);
    }
    el.classList.toggle('tv-status-error', !!error);
    el.textContent = text;
}

/** All jobs (active + recent) that belong to one image of one message, in display order. */
function jobsForImage(chatId, mesId, src) {
    const now = Date.now();
    for (const [key, job] of recentJobs) {
        if (job.until && job.until <= now) recentJobs.delete(key);
    }
    return [...jobs.values(), ...recentJobs.values()]
        .filter(j => j.chatId === chatId && j.mesId === mesId && j.src === src)
        .sort((a, b) => a.n - b.n);
}

/** Builds the one-line status: "⏳ в очереди" or "⏳ #1 в очереди · 🎬 #2 рендерю 0:40". */
function statusLineFor(chatId, mesId, src) {
    const list = jobsForImage(chatId, mesId, src);
    if (!list.length) return { text: '', error: false };
    // Single clip: "⏳ в очереди #2" (queue position). Several clips: "⏳ #1 в очереди · 🎬 #2 рендерю 0:40" (clip numbers).
    const text = list.length === 1
        ? `${list[0].icon} ${list[0].label}${list[0].position ? ` #${list[0].position}` : ''}`.trim()
        : list.map(j => `${j.icon} #${j.n} ${j.label}`.trim()).join(' · ');
    return { text, error: list.some(j => j.error) };
}

function renderStatusFor(chatId, mesId, src) {
    if (currentChatId() !== chatId) return;
    const { text, error } = statusLineFor(chatId, mesId, src);
    renderStatus(findImageWrap(mesId, src), text, { error });
}

function setJobStatus(job, icon, label, { error = false, position = 0 } = {}) {
    job.icon = icon;
    job.label = label;
    job.error = error;
    job.position = position;
    renderStatusFor(job.chatId, job.mesId, job.src);
}

function statusFromResponse(status) {
    switch (status?.status) {
        case 'queued': {
            const pos = Number(status.position);
            return { icon: '⏳', label: 'в очереди', position: Number.isFinite(pos) && pos > 0 ? pos : 0 };
        }
        case 'rendering':
            return status.kind === 'join'
                ? { icon: '🔗', label: `склеиваю ${formatElapsed(status.elapsed)}` }
                : { icon: '🎬', label: `рендерю ${formatElapsed(status.elapsed)}` };
        case 'done':
            return { icon: '✅', label: 'готово' };
        case 'error':
            return { icon: '❌', label: status.error || 'ошибка рендера' };
        default:
            return { icon: '…', label: status?.status || 'неизвестный статус' };
    }
}

function getMessage(mesId) {
    const chat = getContext().chat;
    return Array.isArray(chat) ? chat[mesId] : undefined;
}

/**
 * Per-message state stored in `message.extra.tavern_video`:
 * { jobs: {id: {n, status, deliver, prompt, src, seed, quality, smooth, start_job, video, error, updated}},
 *   chain: [done job ids in completion order], job_id, status, src }
 * `job_id`/`status` mirror the most recently created job (also the v1 format, migrated here).
 */
function getMessageState(message) {
    if (!message) return null;
    if (!message.extra || typeof message.extra !== 'object') message.extra = {};
    let tv = message.extra[MODULE];
    if (!tv || typeof tv !== 'object') tv = message.extra[MODULE] = {};
    if (!tv.jobs || typeof tv.jobs !== 'object') tv.jobs = {};
    if (!Array.isArray(tv.chain)) tv.chain = [];
    if (tv.job_id && !tv.jobs[tv.job_id]) {
        // v1 record → job list
        tv.jobs[tv.job_id] = {
            n: Object.keys(tv.jobs).length + 1,
            status: tv.status || 'queued',
            deliver: tv.deliver || 'chat',
            prompt: tv.prompt || '',
            src: tv.src || '',
            video: tv.video,
            error: tv.error,
            updated: tv.updated || Date.now(),
        };
        if (tv.status === 'done' && !tv.chain.includes(tv.job_id)) tv.chain.push(tv.job_id);
    }
    return tv;
}

/** Job ids of finished clips (chain order); the last one is what ⏩ continues from. */
function doneJobIds(message) {
    const tv = getMessageState(message);
    if (!tv) return [];
    const done = tv.chain.filter(id => tv.jobs[id]?.status === 'done');
    for (const [id, rec] of Object.entries(tv.jobs)) {
        if (rec?.status === 'done' && !done.includes(id)) done.push(id);
    }
    return done;
}

function writeJobRecord(message, jobId, patch) {
    const tv = getMessageState(message);
    const record = { ...(tv.jobs[jobId] || {}), ...patch, updated: Date.now() };
    tv.jobs[jobId] = record;
    tv.job_id = jobId;
    tv.status = record.status;
    if (record.src) tv.src = record.src;
    if (record.status === 'done' && !tv.chain.includes(jobId)) tv.chain.push(jobId);
    return record;
}

async function persistJob(mesId, jobId, patch) {
    const message = getMessage(mesId);
    if (!message) return;
    writeJobRecord(message, jobId, patch);
    try {
        await getContext().saveChat();
    } catch (error) {
        console.warn(LOG, 'saveChat failed', error);
    }
}

/**
 * Seeds for a batch: explicit seed → seed, seed+1, …; empty seed → one random per clip
 * (null for a single clip lets the bridge pick, distinct client-side seeds for several).
 */
function makeSeeds(seed, count) {
    if (seed !== null && seed !== undefined) {
        return Array.from({ length: count }, (_, i) => seed + i);
    }
    if (count === 1) return [null];
    const seeds = new Set();
    while (seeds.size < count) seeds.add(Math.floor(Math.random() * 2147483647));
    return [...seeds];
}

/**
 * POST /video/jobs. Pass either {base64, mime} (start from an image) or {startJob} (continue from that job's last frame).
 */
async function createJob({ base64, mime, startJob, params, seed, chatId, mesId }) {
    const body = {
        prompt: params.prompt,
        sec: params.sec,
        res: params.res,
        seed,
        lora: params.loras.map(l => `${l.name}:${formatStrength(l.strength)}`),
        quality: params.quality,
        smooth: !!params.smooth,
        deliver: params.deliver,
        chat: chatId,
        message_id: mesId,
    };
    if (params.negExtra) body.neg_extra = params.negExtra;
    if (startJob) {
        body.start_job = startJob;
    } else {
        body.image = base64;
        body.image_mime = mime;
    }
    const json = await bridgeFetchJson('/video/jobs', { method: 'POST', body: JSON.stringify(body) });
    if (!json?.id) throw new Error('бридж не вернул id задачи');
    return String(json.id);
}

function makeJobState({ id, chatId, mesId, src, n, deliver, prompt, icon = '⏳', label = 'в очереди' }) {
    return {
        id, key: jobKey(chatId, mesId, id), chatId, mesId, src, n, deliver, prompt,
        icon, label, error: false, errors: 0, timer: null, finished: false, until: 0, position: 0,
    };
}

function startPolling(job) {
    if (jobs.has(job.key)) {
        clearTimeout(jobs.get(job.key).timer);
    }
    recentJobs.delete(job.key);
    job.errors = 0;
    job.finished = false;
    jobs.set(job.key, job);

    const finish = ({ ttl }) => {
        job.finished = true;
        clearTimeout(job.timer);
        jobs.delete(job.key);
        job.until = Date.now() + ttl;
        recentJobs.set(job.key, job);
        setTimeout(() => renderStatusFor(job.chatId, job.mesId, job.src), ttl + 50);
    };

    const tick = async () => {
        let status;
        try {
            status = await bridgeFetchJson(`/video/jobs/${encodeURIComponent(job.id)}`, { method: 'GET' });
            job.errors = 0;
        } catch (error) {
            job.errors += 1;
            console.warn(LOG, `poll failed (${job.errors}/${MAX_POLL_ERRORS})`, error);
            if (job.errors >= MAX_POLL_ERRORS) {
                setJobStatus(job, '❌', `бридж недоступен: ${error.message}`, { error: true });
                await persistJob(job.mesId, job.id, { status: 'error', error: error.message });
                finish({ ttl: ERROR_STATUS_TTL_MS });
                return;
            }
            setJobStatus(job, job.icon, `${job.label} (нет связи, пробую ещё…)`);
            job.timer = setTimeout(tick, POLL_MS);
            return;
        }

        const { icon, label, position = 0 } = statusFromResponse(status);
        switch (status.status) {
            case 'done': {
                setJobStatus(job, icon, label);
                if (job.deliver === 'chat' || job.deliver === 'both') {
                    try {
                        setJobStatus(job, '⬇️', 'загружаю видео в чат…');
                        await deliverToChat(job, status);
                        setJobStatus(job, '✅', 'видео готово');
                        finish({ ttl: DONE_STATUS_TTL_MS });
                        toastr.success('Видео добавлено в сообщение', TOAST_TITLE);
                    } catch (error) {
                        console.error(LOG, 'deliverToChat failed', error);
                        setJobStatus(job, '❌', `не смогла прикрепить видео: ${error.message}`, { error: true });
                        finish({ ttl: ERROR_STATUS_TTL_MS });
                        toastr.error(`Не смогла прикрепить видео: ${error.message}`, TOAST_TITLE);
                    }
                } else {
                    setJobStatus(job, '✅', 'готово, отправлено в телеграм');
                    await persistJob(job.mesId, job.id, { status: 'done' });
                    finish({ ttl: DONE_STATUS_TTL_MS });
                    rescan();
                }
                return;
            }
            case 'error': {
                setJobStatus(job, icon, label, { error: true });
                toastr.error(status.error || 'ошибка рендера', TOAST_TITLE);
                await persistJob(job.mesId, job.id, { status: 'error', error: status.error || '' });
                finish({ ttl: ERROR_STATUS_TTL_MS });
                return;
            }
            default: {
                setJobStatus(job, icon, label, { position });
                job.timer = setTimeout(tick, POLL_MS);
            }
        }
    };

    tick();
}

async function downloadVideoAsBase64(videoUrl) {
    const response = await fetch(videoUrl, { headers: bridgeHeaders() });
    if (!response.ok) throw new Error(`не смогла скачать видео (HTTP ${response.status})`);
    const blob = await response.blob();
    if (!blob.size) throw new Error('видео пустое');
    const dataUrl = await blobToDataUrl(blob);
    return dataUrl.split(',')[1];
}

async function uploadToSillyTavern(name, base64) {
    const response = await fetch('/api/files/upload', {
        method: 'POST',
        headers: getRequestHeaders(),
        body: JSON.stringify({ name, data: base64 }),
    });
    if (!response.ok) {
        throw new Error(`ST не принял файл (HTTP ${response.status}): ${(await response.text()).slice(0, 200)}`);
    }
    const json = await response.json();
    if (!json?.path) throw new Error('ST не вернул путь к файлу');
    return String(json.path);
}

/**
 * Attaches a video to a chat message the ST 1.18+/1.19 way (`extra.media` array,
 * see `ensureMessageMediaIsArray` / `appendMediaToMessage` in public/script.js).
 * Falls back to the legacy `extra.video` string on older builds.
 */
function attachVideoToMessage(message, path, title) {
    if (!message.extra || typeof message.extra !== 'object') message.extra = {};
    const context = getContext();
    const supportsMediaArray = typeof context.ensureMessageMediaIsArray === 'function';
    if (supportsMediaArray) {
        context.ensureMessageMediaIsArray(message);
        if (!Array.isArray(message.extra.media)) message.extra.media = [];
        message.extra.media.push({ type: MEDIA_VIDEO, url: path, title: title || '' });
    } else {
        message.extra.video = path;
        if (title) message.extra.title = title;
    }
}

function rerenderMessageMedia(mesId, message) {
    const context = getContext();
    const mesEl = $(`#chat .mes[mesid="${mesId}"]`);
    if (!mesEl.length) return;
    if (typeof context.appendMediaToMessage === 'function') {
        context.appendMediaToMessage(message, mesEl);
    } else if (typeof context.updateMessageBlock === 'function') {
        context.updateMessageBlock(mesId, message);
    }
}

async function attachUploadedVideo(chatId, mesId, path, title, jobId) {
    if (currentChatId() !== chatId) {
        const list = pendingAttach.get(chatId) ?? [];
        list.push({ mesId, path, title, jobId });
        pendingAttach.set(chatId, list);
        console.info(LOG, 'chat changed while rendering — video will be attached when the chat is opened again');
        return false;
    }
    const message = getMessage(mesId);
    if (!message) throw new Error(`сообщение #${mesId} не найдено`);
    attachVideoToMessage(message, path, title);
    writeJobRecord(message, jobId, { status: 'done', video: path });
    await getContext().saveChat();
    rerenderMessageMedia(mesId, message);
    rescan();
    return true;
}

async function deliverToChat(job, status) {
    const videoUrl = resolveBridgeFileUrl(status.video_url);
    const base64 = await downloadVideoAsBase64(videoUrl);
    const name = `slayvideo_${Date.now()}_${job.id.replace(/[^a-zA-Z0-9_-]/g, '').slice(0, 12)}.mp4`;
    const path = await uploadToSillyTavern(name, base64);
    await attachUploadedVideo(job.chatId, job.mesId, path, job.prompt, job.id);
}

async function flushPendingAttachments() {
    const chatId = currentChatId();
    const list = pendingAttach.get(chatId);
    if (!list?.length) return;
    pendingAttach.delete(chatId);
    for (const item of list) {
        try {
            await attachUploadedVideo(chatId, item.mesId, item.path, item.title, item.jobId);
        } catch (error) {
            console.error(LOG, 'pending attach failed', error);
        }
    }
}

/** Resume polling for jobs saved in the chat (after a reload / chat switch). */
function resumeJobsFromChat() {
    const context = getContext();
    const chatId = currentChatId();
    if (!chatId || !Array.isArray(context.chat)) return;
    context.chat.forEach((message, mesId) => {
        if (!message?.extra?.[MODULE]) return;
        const tv = getMessageState(message);
        for (const [jobId, record] of Object.entries(tv.jobs)) {
            if (!record || ['done', 'error'].includes(record.status)) continue;
            const key = jobKey(chatId, mesId, jobId);
            if (jobs.has(key)) continue;
            console.info(LOG, `resuming job ${jobId} for message #${mesId}`);
            startPolling(makeJobState({
                id: jobId,
                chatId,
                mesId,
                src: record.src || tv.src || '',
                n: Number(record.n) || Object.keys(tv.jobs).indexOf(jobId) + 1,
                deliver: DELIVER.includes(record.deliver) ? record.deliver : 'chat',
                prompt: record.prompt || '',
                icon: '⏳',
                label: 'проверяю статус…',
            }));
        }
    });
}

// ---------------------------------------------------------------------------
// Click flow
// ---------------------------------------------------------------------------

/**
 * Creates `params.count` jobs for one message/image and starts polling each.
 * @param {object} source {base64, mime} or {startJob}
 */
async function launchJobs({ source, params, chatId, mesId, src, wrap }) {
    const message = getMessage(mesId);
    if (!message) throw new Error(`сообщение #${mesId} не найдено`);
    const tv = getMessageState(message);
    const seeds = makeSeeds(params.seed, params.count);
    const created = [];
    let firstError = null;
    for (let i = 0; i < params.count; i++) {
        renderStatus(wrap, params.count > 1 ? `📤 отправляю задачу ${i + 1}/${params.count}…` : '📤 отправляю задачу…');
        try {
            const jobId = await createJob({ ...source, params, seed: seeds[i], chatId, mesId });
            const n = Object.keys(tv.jobs).length + 1;
            writeJobRecord(message, jobId, {
                n,
                status: 'queued',
                deliver: params.deliver,
                prompt: params.prompt,
                src,
                seed: seeds[i],
                sec: params.sec,
                res: params.res,
                quality: params.quality,
                smooth: !!params.smooth,
                start_job: source.startJob || undefined,
            });
            created.push(makeJobState({ id: jobId, chatId, mesId, src, n, deliver: params.deliver, prompt: params.prompt }));
        } catch (error) {
            firstError = firstError || error;
            console.error(LOG, `job ${i + 1}/${params.count} failed`, error);
        }
    }
    if (created.length) {
        try {
            await getContext().saveChat();
        } catch (error) {
            console.warn(LOG, 'saveChat failed', error);
        }
    }
    for (const job of created) startPolling(job);
    renderStatusFor(chatId, mesId, src);
    if (firstError) {
        const msg = created.length
            ? `часть задач не создана (${created.length}/${params.count} ушло): ${firstError.message}`
            : firstError.message;
        toastr.error(msg, TOAST_TITLE);
        if (!created.length) throw firstError;
    }
}

/** GET /video/jobs/<id>/last → PNG of the last frame of a finished job. */
async function fetchLastFrame(jobId) {
    const response = await fetch(bridgeUrl(`/video/jobs/${encodeURIComponent(jobId)}/last`), { headers: bridgeHeaders() });
    if (!response.ok) {
        const text = await response.text().catch(() => '');
        throw new Error(`бридж не отдал последний кадр (HTTP ${response.status})${text ? `: ${text.slice(0, 120)}` : ''}`);
    }
    const blob = await response.blob();
    const mime = (blob.type || '').split(';')[0].trim().toLowerCase() || 'image/png';
    if (!mime.startsWith('image/')) throw new Error(`последний кадр пришёл как ${mime}, а не картинка`);
    if (!blob.size) throw new Error('последний кадр пустой');
    const dataUrl = await blobToDataUrl(blob);
    return { base64: dataUrl.split(',')[1], mime, dataUrl };
}

/**
 * ⏩ Продолжить: last frame of `fromJobId` → vision model → popup → POST start_job.
 * @param {object} opts
 * @param {number} opts.mesId
 * @param {string} opts.fromJobId
 * @param {HTMLElement} opts.btn
 * @param {HTMLImageElement|null} [opts.img]  source SLAY image (for the instruction / status anchor)
 */
async function onContinueClick({ mesId, fromJobId, btn, img = null }) {
    const settings = getSettings();
    const chatId = currentChatId();
    const message = getMessage(mesId);
    if (!message) {
        toastr.error(`Сообщение #${mesId} не найдено`, TOAST_TITLE);
        return;
    }
    const tv = getMessageState(message);
    const record = tv.jobs[fromJobId];
    if (!record || record.status !== 'done') {
        toastr.error('Этот ролик ещё не готов — продолжать не с чего', TOAST_TITLE);
        return;
    }
    if (!String(settings.bridgeUrl || '').trim()) {
        toastr.error('Укажи адрес бриджа в настройках «🎬 Видео»', TOAST_TITLE);
        return;
    }
    if (btn.classList.contains('tv-busy')) return;

    const src = img?.getAttribute('src') || record.src || tv.src || '';
    const anchor = findImageWrap(mesId, src);
    btn.classList.add('tv-busy');
    btn.disabled = true;
    try {
        renderStatus(anchor, '🧠 придумываю продолжение…');
        await fetchLoraCatalog();
        const frame = await fetchLastFrame(fromJobId);
        const sourceImg = img ?? Array.from(document.querySelectorAll(`#chat .mes[mesid="${mesId}"] .mes_text img[data-iig-instruction]`))
            .find(i => i.getAttribute('src') === src) ?? null;
        const instruction = sourceImg?.getAttribute('data-iig-instruction') || '';
        const text = stripHtml(message?.mes ?? '').slice(-MAX_TEXT_CHARS);
        const answer = await askVisionModel({
            base64: frame.base64, mime: frame.mime, instruction, text, continueFrom: record.prompt || '',
        });

        renderStatusFor(chatId, mesId, src);
        const params = await showJobPopup({ prompt: answer.prompt, loras: answer.loras, previewSrc: frame.dataUrl, title: '⏩ Продолжить' });
        if (!params) return;

        await launchJobs({ source: { startJob: fromJobId }, params, chatId, mesId, src, wrap: anchor });
    } catch (error) {
        console.error(LOG, error);
        renderStatus(anchor, `❌ ${error?.message || error}`, { error: true });
        toastr.error(String(error?.message || error), TOAST_TITLE);
    } finally {
        btn.classList.remove('tv-busy');
        btn.disabled = false;
    }
}

// ---------------------------------------------------------------------------
// 🔗 Склеить: finished clips of one message → POST /video/join → one more video on the message
// ---------------------------------------------------------------------------

function pluralClips(n) {
    const mod10 = n % 10;
    const mod100 = n % 100;
    if (mod10 === 1 && mod100 !== 11) return `${n} ролик`;
    if (mod10 >= 2 && mod10 <= 4 && (mod100 < 10 || mod100 >= 20)) return `${n} ролика`;
    return `${n} роликов`;
}

/** Finished clips of a message in creation order: [{id, record}]. */
function doneClipsInOrder(tv) {
    return Object.entries(tv.jobs)
        .filter(([, record]) => record?.status === 'done')
        .sort((a, b) => (Number(a[1].n) || 0) - (Number(b[1].n) || 0) || (a[1].updated || 0) - (b[1].updated || 0))
        .map(([id, record]) => ({ id, record }));
}

/** The clip, everything it continues (start_job links back) and everything continued from it — what 🔗 pre-selects. */
function lineageOf(tv, jobId) {
    const picked = new Set();
    let current = jobId;
    while (current && tv.jobs[current] && !picked.has(current)) {
        picked.add(current);
        current = tv.jobs[current].start_job;
    }
    const queue = [jobId];
    while (queue.length) {
        const id = queue.shift();
        for (const [childId, record] of Object.entries(tv.jobs)) {
            if (record?.start_job === id && !picked.has(childId)) {
                picked.add(childId);
                queue.push(childId);
            }
        }
    }
    return picked;
}

function clipMeta(record) {
    const bits = [];
    if (record.kind === 'join') {
        bits.push(`🔗 склейка × ${Array.isArray(record.parts) ? record.parts.length : '?'}`);
    } else {
        if (record.sec) bits.push(`${record.sec} с`);
        if (record.quality === 'hi') bits.push('лучше');
        if (record.smooth) bits.push('32 fps');
        if (record.start_job) bits.push('⏩');
    }
    return bits.join(' · ');
}

/**
 * Popup with a checklist of the message's finished clips (order = order in the message), seam type and destination.
 * @returns {Promise<{jobs: string[], xfade: number, deliver: string}|null>}
 */
async function showJoinPopup({ clips, preselected }) {
    const settings = getSettings();
    const rows = clips.map(({ id, record }) => {
        const checked = preselected.has(id) ? ' checked' : '';
        const promptHead = String(record.prompt || '').replace(/\s+/g, ' ').trim().slice(0, 90);
        return `<label class="tv-join-row">
            <input type="checkbox" class="tv-join-check" value="${escapeHtml(id)}"${checked}>
            <b>#${escapeHtml(record.n ?? '?')}</b>
            <span class="tv-join-meta">${escapeHtml(clipMeta(record))}</span>
            <span class="tv-join-prompt" title="${escapeHtml(record.prompt || '')}">${escapeHtml(promptHead)}</span>
        </label>`;
    }).join('');
    const xfadeOptions = XFADE_OPTIONS.map(o => `<option value="${o.value}"${Number(settings.xfade) === o.value ? ' selected' : ''}>${o.label}</option>`).join('');
    const deliverLabels = { chat: 'чат', tg: 'телеграм', both: 'оба' };
    const deliverRadios = DELIVER.map(v => `<label><input type="radio" name="tv_j_deliver" value="${v}"${v === settings.deliver ? ' checked' : ''}> ${deliverLabels[v]}</label>`).join('');

    const wrapper = document.createElement('div');
    wrapper.className = 'tv-popup';
    wrapper.innerHTML = `
        <h3>🔗 Склеить</h3>
        <div class="tv-lora-head"><span>Ролики</span><span class="tv-hint">галочка = попадёт в склейку, порядок = порядок в сообщении</span></div>
        <div class="tv-join-list">${rows}</div>
        <p class="tv-hint">⏩-продолжения склеиваются кадр в кадр (ничего не повторяется). Разный fps выравнивается по большему, размер — по первому ролику. Без перерендера, несколько секунд.</p>
        <div class="tv-radios">
            <label>Стык <select id="tv_j_xfade" class="text_pole">${xfadeOptions}</select></label>
            <span class="tv-radios-sep"></span>
            <span>Куда:</span>${deliverRadios}
        </div>`;

    let captured = null;
    const capture = () => {
        captured = {
            jobs: Array.from(wrapper.querySelectorAll('.tv-join-check:checked')).map(el => el.value),
            xfade: clampFloat(wrapper.querySelector('#tv_j_xfade').value, 0, 1, 0),
            deliver: wrapper.querySelector('input[name="tv_j_deliver"]:checked')?.value || settings.deliver,
        };
    };

    const result = await callGenericPopup(wrapper, POPUP_TYPE.CONFIRM, '', {
        okButton: 'Склеить',
        cancelButton: 'Отмена',
        wide: true,
        allowVerticalScrolling: true,
        onClosing: (popup) => {
            if (popup.result === POPUP_RESULT.AFFIRMATIVE) {
                capture();
                if (captured.jobs.length < 2) {
                    toastr.warning('Отметь хотя бы два ролика', TOAST_TITLE);
                    return false;
                }
            }
            return true;
        },
    });

    if (result !== POPUP_RESULT.AFFIRMATIVE || !captured) return null;
    settings.xfade = captured.xfade;
    saveSettingsDebounced();
    return captured;
}

/**
 * 🔗 under a video: pick clips → POST /video/join → poll like any job → the joined video is attached to the same message.
 * @param {object} opts
 * @param {number} opts.mesId
 * @param {string} opts.jobId   the clip whose bar was clicked (its lineage is pre-selected)
 * @param {HTMLElement} opts.btn
 */
async function onJoinClick({ mesId, jobId, btn }) {
    const settings = getSettings();
    const chatId = currentChatId();
    const message = getMessage(mesId);
    if (!message) {
        toastr.error(`Сообщение #${mesId} не найдено`, TOAST_TITLE);
        return;
    }
    const tv = getMessageState(message);
    const clips = doneClipsInOrder(tv);
    if (clips.length < 2) {
        toastr.info('В этом сообщении пока один готовый ролик — склеивать не с чем', TOAST_TITLE);
        return;
    }
    if (!String(settings.bridgeUrl || '').trim()) {
        toastr.error('Укажи адрес бриджа в настройках «🎬 Видео»', TOAST_TITLE);
        return;
    }
    if (btn.classList.contains('tv-busy')) return;

    const src = tv.jobs[jobId]?.src || tv.src || '';
    const anchor = findImageWrap(mesId, src);
    btn.classList.add('tv-busy');
    btn.disabled = true;
    try {
        const params = await showJoinPopup({ clips, preselected: lineageOf(tv, jobId) });
        if (!params) return;
        renderStatus(anchor, '📤 отправляю склейку…');
        const prompt = `🔗 склейка: ${pluralClips(params.jobs.length)}`;
        const body = { jobs: params.jobs, xfade: params.xfade, deliver: params.deliver, chat: chatId, message_id: mesId, prompt };
        const json = await bridgeFetchJson('/video/join', { method: 'POST', body: JSON.stringify(body) });
        if (!json?.id) throw new Error('бридж не вернул id задачи');
        const id = String(json.id);
        const n = Object.keys(tv.jobs).length + 1;
        writeJobRecord(message, id, {
            n, status: 'queued', deliver: params.deliver, prompt, src,
            kind: 'join', parts: params.jobs, xfade: params.xfade,
        });
        try {
            await getContext().saveChat();
        } catch (error) {
            console.warn(LOG, 'saveChat failed', error);
        }
        startPolling(makeJobState({ id, chatId, mesId, src, n, deliver: params.deliver, prompt, icon: '🔗', label: 'склеиваю…' }));
        renderStatusFor(chatId, mesId, src);
    } catch (error) {
        console.error(LOG, error);
        renderStatus(anchor, `❌ ${error?.message || error}`, { error: true });
        toastr.error(String(error?.message || error), TOAST_TITLE);
    } finally {
        btn.classList.remove('tv-busy');
        btn.disabled = false;
    }
}

async function onVideoButtonClick(img, wrap, btn) {
    const settings = getSettings();
    const mesEl = img.closest('.mes');
    const mesId = Number(mesEl?.getAttribute('mesid'));
    if (!Number.isInteger(mesId)) {
        toastr.error('Не нашла сообщение для этой картинки', TOAST_TITLE);
        return;
    }
    const context = getContext();
    const chatId = currentChatId();
    const message = context.chat?.[mesId];
    const src = img.getAttribute('src') || '';

    if (!String(settings.bridgeUrl || '').trim()) {
        toastr.error('Укажи адрес бриджа в настройках «🎬 Видео»', TOAST_TITLE);
        return;
    }
    if (btn.classList.contains('tv-busy')) return;

    btn.classList.add('tv-busy');
    btn.disabled = true;
    try {
        renderStatus(wrap, '🧠 придумываю промпт…');
        await fetchLoraCatalog();
        const { base64, mime } = await imageToBase64(img);
        const instruction = img.getAttribute('data-iig-instruction') || '';
        const text = stripHtml(message?.mes ?? '').slice(-MAX_TEXT_CHARS);
        const answer = await askVisionModel({ base64, mime, instruction, text });

        renderStatusFor(chatId, mesId, src);
        const params = await showJobPopup({ prompt: answer.prompt, loras: answer.loras, previewSrc: img.currentSrc || src });
        if (!params) return;

        await launchJobs({ source: { base64, mime }, params, chatId, mesId, src, wrap });
    } catch (error) {
        console.error(LOG, error);
        renderStatus(wrap, `❌ ${error?.message || error}`, { error: true });
        toastr.error(String(error?.message || error), TOAST_TITLE);
    } finally {
        btn.classList.remove('tv-busy');
        btn.disabled = false;
    }
}

// ---------------------------------------------------------------------------
// DOM: button injection
// ---------------------------------------------------------------------------

function getWrap(img) {
    return img.closest('.iig-img-wrap, .tv-img-wrap');
}

function attachButton(img) {
    const src = img.getAttribute('src') || '';
    if (!src || src.includes('[IMG:GEN') || src.startsWith('data:image/svg')) return; // SLAY placeholder, not generated yet
    if (img.classList.contains('iig-error-image') || img.closest('.iig-error-placeholder')) return;
    if (!img.parentNode) return;

    let wrap = getWrap(img);
    if (!wrap) {
        wrap = document.createElement('span');
        wrap.className = 'tv-img-wrap';
        img.parentNode.insertBefore(wrap, img);
        wrap.appendChild(img);
    }
    const mesId = Number(img.closest('.mes')?.getAttribute('mesid'));

    if (!wrap.querySelector(':scope > .tv-btn')) {
        const btn = document.createElement('button');
        btn.type = 'button';
        btn.className = 'tv-btn';
        btn.title = 'Сделать видео из этой картинки';
        btn.setAttribute('aria-label', 'Сделать видео');
        btn.textContent = '🎬';
        btn.addEventListener('click', (event) => {
            event.preventDefault();
            event.stopPropagation();
            onVideoButtonClick(img, wrap, btn);
        });
        wrap.appendChild(btn);

        // Restore the status line of running / recently finished jobs after a re-render.
        if (Number.isInteger(mesId)) {
            const { text, error } = statusLineFor(currentChatId(), mesId, src);
            if (text) renderStatus(wrap, text, { error });
        }
    }

    if (Number.isInteger(mesId)) syncContinueButton(img, wrap, mesId);
}

/** ⏩ next to 🎬 — only when the message has a finished clip to continue from. */
function syncContinueButton(img, wrap, mesId) {
    const message = getMessage(mesId);
    const done = message?.extra?.[MODULE] ? doneJobIds(message) : [];
    const existing = wrap.querySelector(':scope > .tv-cont-btn');
    if (!done.length) {
        existing?.remove();
        return;
    }
    const lastJobId = done[done.length - 1];
    if (existing) {
        existing.dataset.jobId = lastJobId;
        return;
    }
    const btn = document.createElement('button');
    btn.type = 'button';
    btn.className = 'tv-cont-btn';
    btn.dataset.jobId = lastJobId;
    btn.title = 'Продолжить движение с последнего кадра готового ролика';
    btn.setAttribute('aria-label', 'Продолжить');
    btn.textContent = '⏩';
    btn.addEventListener('click', (event) => {
        event.preventDefault();
        event.stopPropagation();
        onContinueClick({ mesId, fromJobId: btn.dataset.jobId, btn, img });
    });
    wrap.appendChild(btn);
}

/** 🔗 in a video bar: present when the message has at least two finished clips, points at the bar's own clip. */
function syncJoinButton(bar, canJoin, jobId, mesId) {
    let join = bar.querySelector(':scope > .tv-video-join');
    if (!canJoin) {
        join?.remove();
        return;
    }
    if (join) {
        join.dataset.jobId = jobId;
        return;
    }
    join = document.createElement('button');
    join.type = 'button';
    join.className = 'tv-video-join menu_button';
    join.dataset.jobId = jobId;
    join.title = 'Склеить ролики этого сообщения в одно видео (этот ролик и его продолжения отмечены заранее)';
    join.textContent = '🔗 Склеить';
    join.addEventListener('click', (event) => {
        event.preventDefault();
        event.stopPropagation();
        onJoinClick({ mesId, jobId: join.dataset.jobId, btn: join });
    });
    bar.appendChild(join);
}

/** "⏩ Продолжить" (+ "🔗 Склеить") bar under every attached video that came from one of our jobs. */
function scanVideoBars() {
    const chat = getContext().chat;
    if (!Array.isArray(chat)) return;
    for (const mesEl of document.querySelectorAll('#chat .mes')) {
        const mesId = Number(mesEl.getAttribute('mesid'));
        const message = chat[mesId];
        if (!message?.extra?.[MODULE]) continue;
        const tv = getMessageState(message);
        const byVideo = new Map();
        for (const [jobId, record] of Object.entries(tv.jobs)) {
            if (record?.status === 'done' && record.video) byVideo.set(record.video, jobId);
        }
        if (!byVideo.size) continue;
        const canJoin = byVideo.size >= 2;
        for (const container of mesEl.querySelectorAll('.mes_media_wrapper .mes_video_container')) {
            const index = Number(container.getAttribute('data-index'));
            const url = message.extra?.media?.[index]?.url;
            const jobId = url ? byVideo.get(url) : undefined;
            const existing = container.querySelector(':scope > .tv-video-bar');
            if (!jobId) {
                existing?.remove();
                continue;
            }
            if (existing) {
                existing.querySelector('.tv-video-cont').dataset.jobId = jobId;
                syncJoinButton(existing, canJoin, jobId, mesId);
                continue;
            }
            const bar = document.createElement('div');
            bar.className = 'tv-video-bar';
            const btn = document.createElement('button');
            btn.type = 'button';
            btn.className = 'tv-video-cont menu_button';
            btn.dataset.jobId = jobId;
            btn.title = 'Продолжить движение с последнего кадра этого ролика';
            btn.textContent = '⏩ Продолжить';
            btn.addEventListener('click', (event) => {
                event.preventDefault();
                event.stopPropagation();
                onContinueClick({ mesId, fromJobId: btn.dataset.jobId, btn });
            });
            bar.appendChild(btn);
            syncJoinButton(bar, canJoin, jobId, mesId);
            container.appendChild(bar);
        }
    }
}

function scanChat() {
    const images = document.querySelectorAll('#chat .mes .mes_text img[data-iig-instruction]');
    for (const img of images) {
        try {
            attachButton(img);
        } catch (error) {
            console.warn(LOG, 'attachButton failed', error);
        }
    }
    try {
        scanVideoBars();
    } catch (error) {
        console.warn(LOG, 'scanVideoBars failed', error);
    }
}

const rescan = debounce(scanChat, 150);

function observeChat() {
    const chatEl = document.getElementById('chat');
    if (!chatEl) return;
    const observer = new MutationObserver((mutations) => {
        for (const mutation of mutations) {
            if (mutation.type === 'attributes') {
                rescan();
                return;
            }
            for (const node of mutation.addedNodes) {
                if (node.nodeType !== Node.ELEMENT_NODE) continue;
                const el = /** @type {Element} */ (node);
                if (el.classList?.contains('tv-btn') || el.classList?.contains('tv-cont-btn') || el.classList?.contains('tv-status') || el.classList?.contains('tv-video-bar')) continue;
                rescan();
                return;
            }
        }
    });
    observer.observe(chatEl, { childList: true, subtree: true, attributes: true, attributeFilter: ['src', 'data-iig-instruction'] });
}

// ---------------------------------------------------------------------------
// Init
// ---------------------------------------------------------------------------

jQuery(async () => {
    getSettings();
    bindSettingsUi();
    observeChat();

    const renderEvents = [
        'CHAT_CHANGED',
        'CHARACTER_MESSAGE_RENDERED',
        'USER_MESSAGE_RENDERED',
        'MESSAGE_UPDATED',
        'MESSAGE_EDITED',
        'MESSAGE_SWIPED',
        'MESSAGE_RECEIVED',
        'MESSAGE_SENT',
        'MORE_MESSAGES_LOADED',
        'GENERATION_ENDED',
    ];
    for (const name of renderEvents) {
        if (event_types[name]) eventSource.on(event_types[name], () => rescan());
    }
    eventSource.on(event_types.CHAT_CHANGED, async () => {
        try {
            await flushPendingAttachments();
            resumeJobsFromChat();
        } catch (error) {
            console.warn(LOG, 'CHAT_CHANGED handler failed', error);
        }
        rescan();
    });

    scanChat();
    resumeJobsFromChat();
    refreshLoraCatalog();
    console.info(LOG, 'loaded');
});
